Капельницы, патронташи, полевик и парамед
frosty-dev/white pull request #1014
Opened 2022-06-09 19:44 UTC by FelineMistress

## About The Pull Request
1) Коробки с ружейными патронами заменены на Патронташи, помимо хранения в рюкзаках их можно крепить на карманы или ремень (средний предмет) и при клике по ним пустой рукой сразу достается первый патрон в списке, их так же можно произвести в сб и карго протолате после исследования технологий СБ
2) Некоторое оружие (штурмовые винтовки) в богатом бриге было заменено на аналоги в связи с его чрезмерной убойностью
3) Новый спрайт Экстренному шву (нитки низкого качества в аварийных аптечках), немного бледнее обычных, так же немного повышена их эффективность в остановке кровотечений.
4) Вследствие разжирения экипажа на поясах для инструментов (мед, инж и уни) появилось дополнительное место для 8 предмета, можете выдохнуть.
5) Капельницы теперь складные, их можно взять в руки (как в одну, так и в две) - для этого ПУСТУЮ капельницу нужно перетянуть на себя, по аналогу с подключением СНАРЯЖЕННОЙ капельницы. Держа ее в руках двумя руками, капельницу так же можно использовать в бою, урон средне-низкий имеют эффект отбрасывания (только в двуручном хвате). Новые капельницы можно производить в мед фабрикаторе.
6) Киборги теперь могут подключать капельницы, а так же переносить пакеты с кровью манипулятором для хим стаканов. При клике боргом по сложенной капельнице она раскроется.
7) Прикомандированные к отделам офицеры СБ отображаются в мониторинге персонала не коричневым цветом, а красным как и положено.
8) Полевой медик получил свой собственный шкафчик в бриге, туда была перенесена часть его экипировки и складированы запасные комплекты одежды и части снаряжения. Открыть его может только Полевик, Варден и ХоС, но не офицеры. Так же он получил специальную гарнитуру-бабочку и комплект различных головных уборов (шлем, берет и кепку - ура, шляпы!)
9) Стартовая экипировка парамедика была пересмотрена, теперь его пояс не бесполезный набор предметов, который хочется тихонько прикопать в уголке. Он получил урезанный комплект хирургии, немного лекарств и пенал с 5 адреналиновыми медипенами. Теперь парамедик может оказать реальную помощь на месте происшествия.
10) Полевой медик и парамедик получили медицинские перчатки 3 уровня облегчающие перемещение тел волоком (напоминаем, для того чтобы цель не истекала кровью ее все еще нужно перевозить на каталке или на себе), этот бонус не распространяется на агрессивный захват - он все так же замедляет
11) Фикс отображения научного ПНВ на космонавтике
12) У шлемов появилась косметическая функция отображения прически (и моих любимых ушек), для смены отображения нужно нажать на шлем через Alt+Клик или ПКМ или контекстное меню (поправить прическу)

![2022-06-06_21-18-25](https://user-images.githubusercontent.com/87654572/172929387-5a8c5573-e897-4a1b-bca6-f454dc4b980c.png)

![2022-06-09_11-24-48](https://user-images.githubusercontent.com/87654572/172929440-177f4261-4b65-4d53-a68a-a6279998fa1f.png)

![2022-06-09_11-45-03](https://user-images.githubusercontent.com/87654572/172929474-30061b7d-1263-42be-a7c2-26821642a3f7.png)

2022-06-09 20:00 UTC, Alexs410 requested changes
Забирать у парамеда формальдегид - лишнее.

2022-06-09 20:00 UTC, FelineMistress commented
нету гринтекста!

2022-06-09 20:04 UTC, merged

2022-06-09 20:33 UTC, Alexs410 commented on code/game/machinery/doors/windowdoor.dm
> +	damage_deflection = 16
Нахуя? Чтобы зэки ебались полчаса с выходом?

2022-06-09 20:33 UTC, Alexs410 commented on code/modules/mob/living/simple_animal/bot/secbot.dm
> +	health = 50
Ну зачем? То, что бипски можно сломать ради батона - норма, и ставить 50 - слишком. 35 норм еще будет.

2022-06-09 20:33 UTC, Alexs410 commented on white/Feline/code/general/equipment_all.dm
> +	STR.max_items = 7
А 7 это не много для карманов? Хотя учитывая ДВОЙНОЙ бандольер. 
(И да, на карты лучше по одному патронташу, остальное коробками забить. Иначе дробовиков меньше, чем патронташей.)

2022-06-10 00:54 UTC, AxapooH commented
Помянем последние, кроме калаша, штурмовые винтовки на вайте.