No more MODSuits, теперь это МУВ-Скафандры
frosty-dev/white pull request #1324
Opened 2022-08-18 16:11 UTC by Fesiks

Фулл перевод MODSuits
Я не смог избавиться от THE в названии управляющих модулях

2022-08-18 16:41 UTC, Valtosin requested changes
посмотри

2022-08-18 16:41 UTC, Valtosin commented on code/modules/mod/mod_control.dm
> +		CRASH("[src] пытался поменять внешний вид когда активен!")
это оставить на ангельском

2022-08-18 16:41 UTC, Valtosin commented on code/modules/mod/mod_construction.dm
> +	name = "МУВ [used_theme.name] внешняя обшивка"
тут использовать ru_name

2022-08-18 16:41 UTC, Valtosin commented on code/modules/mod/mod_theme.dm
> +	var/name = "стандартный"
вероятно ломает иконки, нужно оставить name на английском и добавить ru_name на русском

2022-08-18 18:45 UTC, Valtosin commented
да

2022-08-18 18:47 UTC, Fesiks commented
Изменений не увидел, всё также срёт ошибками

2022-08-18 18:54 UTC, Fesiks commented
это может быть связано с уже текущей проблемой с одинаковыми скафандрами ЕРТ

2022-08-19 09:43 UTC, FelineMistress reviewed
Часть первая, где то половина, я пока притомился

2022-08-19 09:43 UTC, FelineMistress commented on code/modules/mod/mod_theme.dm
> +		Этот полностью артикулированный титановый экзоскелет - любимый скафандр от Скарборовы Руки для людей доставляющих боеприпасы, \
Изначально разрабатывался для оперативного снабжения боевых экзокостюмов боеприпасами на поле боя.

2022-08-19 09:43 UTC, FelineMistress commented on code/modules/mod/mod_theme.dm
> +		нехватку защиты от космоса, он компенсирует в прочности и гибкости. Основная особенность \
Из серьезных недостатков можно признать полное отсутствие защиты от окружающей среды и космоса, однако это компенсируется хорошей защитой и адаптивностью конструкции. Главная особенность

2022-08-19 09:43 UTC, FelineMistress commented on code/modules/mod/mod_theme.dm
> +		этот скафандра - два манипулятора, тщательно синхронизированы с мыслями пользователя и \
этого экзоскелета - два манипулятора, синхронизированных с мыслями пользователя и \

2022-08-19 09:43 UTC, FelineMistress commented on code/modules/mod/mod_theme.dm
> +		почти точно дублируют свои движения. Ими управляет моймер, искусственный аналог мышц, \
дублирующих его движения. Такой результат достигается благодаря синтетическим мышцам, управляемых контролером. \

2022-08-19 09:43 UTC, FelineMistress commented on code/modules/mod/mod_theme.dm
> +		требующий большого количества энергии для работы; время от времени выпускющий искры под нагрузкой с большой мощностью. \
К недостаткам синтетических мышц можно отнести высокое энергопотребление и энергетические пробои возникающие в шквале искр при чрезмерной нагрузке. \

2022-08-19 09:43 UTC, FelineMistress commented on code/modules/mod/mod_theme.dm
> +		Скафандр способен поднять 250 тонн. Даже ноги в скафандре настроены на невероятную мощность. \
Экзоскелет способен поднять до 250 тонн.
Сервоприводы опорных конечностей так же способны выдержать огромные нагрузки без потери производительности. \

2022-08-19 09:43 UTC, FelineMistress commented on code/modules/mod/mod_theme.dm
> +		Пользователь может работать на больших скоростях гораздо дольше, чем неподходящий эквивалент. \
чем прочие аналоги. \

2022-08-19 09:43 UTC, FelineMistress commented on code/modules/mod/mod_theme.dm
> +		Многие скажут, что погрузка груза - скучная работа. Вы больше не можете так думать."
Эта модель разубедит вас в этом."

2022-08-19 09:43 UTC, FelineMistress commented on code/modules/mod/mod_theme.dm
> +	desc = "Легкий скафандр от ДеФорест Медицинской Корпорации, позволяющий быстрее передвигатся."
"Легкий скафандр от ДеФорест Мед Корп, с облегченным каркасом и модернизированной двигательной системой."

2022-08-19 09:43 UTC, FelineMistress commented on code/modules/mod/mod_theme.dm
> +	extended_desc = "Легкий скафандр производства ДеФорест Медицинской Корпорации, основанный на работе \
"Легкий скафандр производства ДеФорест Мед Корп, основанный на разработках \

2022-08-19 09:43 UTC, FelineMistress commented on code/modules/mod/mod_theme.dm
> +		Накамура Инженерия. Новейшие технологии были использованы в этом скафандре, чтобы сделать его защищенным против \
Инженеринг
чтобы максимизировать защиту против \

2022-08-19 09:43 UTC, FelineMistress commented on code/modules/mod/mod_theme.dm
> +		аллергенов, воздушных токсинов и обычныех патогенов. Основным активом этого скафандра является скорость, \
патогенов > вирусов
При разработке данного скафандра основным приоритетом являлась снижение замедления скорости перемещения. \

2022-08-19 09:43 UTC, FelineMistress commented on code/modules/mod/mod_theme.dm
> +		мощные сервоприводы и приводы из углеродного волокна. Хотя брони тут используется очень мало, \
Результат был достигнут благодаря мощным сервоприводам и использованию углеродного волокна в конструкции каркаса. В качестве платы пришлось поскупиться стандартными бронелистами и

2022-08-19 09:43 UTC, FelineMistress commented on code/modules/mod/mod_theme.dm
> +		он невероятно кислотостойкий. Однако, он немного более требователен к мощности, чем гражданские модели, \
ограничиться кислотостойкой обшивкой. Энергопотребление так же более повышено по сравнению с гражданскими образцами."

2022-08-19 09:43 UTC, FelineMistress commented on code/modules/mod/mod_theme.dm
> +		и слаб против пальцев, тыкающих по стеклу."
просто убери эту строку

2022-08-19 09:43 UTC, FelineMistress commented on code/modules/mod/mod_theme.dm
> +	desc = "Усовершенствованная версия медицинского скафандра ДеФорест Медицинской корпорации, предназначенная для быстрого спасения тел из самых опасных сред."
ДеФорест Мед Корп

2022-08-19 09:43 UTC, FelineMistress commented on code/modules/mod/mod_theme.dm
> +		как и в базовой версии, дают парамедикам невероятную скорость, но те же самые сервоприводы также находятся в руках, \
базовой комплектации
в дополнение к этому аналогичные сервоприводы расположены на руках скафандра, \

2022-08-19 09:43 UTC, FelineMistress commented on code/modules/mod/mod_theme.dm
> +		позволяя пользователю быстро носить даже самых тяжелых членов экипажа с помощью этого скафандра, \
переносить
в конце точка

2022-08-19 09:43 UTC, FelineMistress commented on code/modules/mod/mod_theme.dm
> +		и при этом полностью защищищая от химических и термальных угроз. \
Предоставляет крайне высокую защиту от ...

2022-08-19 09:43 UTC, FelineMistress commented on code/modules/mod/mod_theme.dm
> +		Он немного более требователен к мощности, чем гражданские модели, и слаб к пальцам, стучащим по стеклу."
про отпечатки пальцев убрать

2022-08-19 09:43 UTC, FelineMistress commented on code/modules/mod/mod_theme.dm
> +	name = "исследовательский"
научный

2022-08-19 09:43 UTC, FelineMistress commented on code/modules/mod/mod_theme.dm
> +	desc = "Частный военный скафандр Аусек Арсенал, предназначенный для взрывотехники. Громоздкий, но экспансивный."
Военный скафандр специального назначения от Ауссек Армори, предназначенный для работы со взрывчатыми веществами. Тяжелый и очень стойкий.

2022-08-19 10:03 UTC, Boroda2228 commented on code/modules/mod/mod_theme.dm
> +		позволяя пользователю быстро носить даже самых тяжелых членов экипажа с помощью этого скафандра, \
"Улучшенная, бронированная версия медицинского скафандра корпорации ДеФорест," (два раза медицинского выходит, не очень красиво)
"предназначенА (версия скафандра предназначена потому что) для ...

2022-08-19 10:13 UTC, Boroda2228 commented on code/modules/mod/mod_theme.dm
> +	var/desc = "Гражданский скафандр от Накамура Инженерия, не предлагает ничего, кроме немного более быстрого движения."
Все эти штуки пишутся с "И" потому что это транскрипция, а не транслитерация.  Плюс, согласно БЭС:
ИНЖИНИРИНГ (англ. engineering, от лат. ingenium - изобретательность; выдумка; знания), одна из форм международных коммерческих связей в сфере науки и техники, основное направление которой - предоставление услуг по доведению научно-исследовательских и опытно-конструкторских разработок до стадии производства.

2022-08-19 10:17 UTC, Boroda2228 commented on code/modules/mod/mod_theme.dm
> +	extended_desc = "Классика Накамура Инженерия, и, конечно, их притязания на славу. Эта модель является \
"...с защитой от электричества и высоких температур."

2022-08-19 11:42 UTC, Boroda2228 reviewed
почитал кое-что, чем смог, тем помог

2022-08-19 11:42 UTC, Boroda2228 commented on code/modules/mod/mod_theme.dm
> +		Этот скафандр предназначен для исследования взрывчатых веществ, построенный невероятно громоздким и герметичным. \
Этот скафандр предназначен для работы со взрывчатыми веществами, что делает его громоздким, но отлично защищенным. 
Well-covering - хорошее покрытие

2022-08-19 11:42 UTC, Boroda2228 commented on code/modules/mod/mod_theme.dm
> +		сложенные в бутерброд для обеспечиваемя инертного слоя, который рассеивает кинетическую энергию в скафандре; \
Не бутерброд. Например: "Скафандр оснащён пласталевой композитной бронёй с промежуточным инертным слоем, призванным рассеивать кинетическую энергию в костюме, отводя её от пользователя."
Можно и лучше сформулировать, но это более точный перевод. 
При чём тут "химический сканирующий массив" я и сам не понял, по смыслу не особо подходит.

2022-08-19 11:42 UTC, Boroda2228 commented on code/modules/mod/mod_theme.dm
> +		ракет и артиллериии, все взрывное сопротивление в основном работает,но только чтобы сохранить пользователя целым, но не живым.  \
всё взрывное сопротивление в основном работает чтобы сохранить тело пользователя целым, а не живым.

2022-08-19 11:42 UTC, Boroda2228 commented on code/modules/mod/mod_theme.dm
> +	desc = "Защитный скафандр Ападайн Технологии, обеспечивающий защиту от ударов и более быструю скорость, за счет подъёмной способности."
...Ападайн Технолоджис
шок протекшон - разве не защита от стана? или от электричества? не уверен что от удара, это бы проверить .
...бОльшую скорость ценой вместимости хранилища.

2022-08-19 11:42 UTC, Boroda2228 commented on code/modules/mod/mod_theme.dm
> +		враждебные единицы. Этот скафандр был создан с покрытием, достаточно прочным для пожаров или агрессивных сред, \
не знаю как "ситуация" превратилась в "единицу".
 Скафандр был оснащён покрытием

2022-08-19 11:42 UTC, Boroda2228 commented on code/modules/mod/mod_theme.dm
> +		позволяя скафандру выполнять больше работы по переноске веса. Однако, системы, используемые в этих скафандрах более  \
...однако системы используемые в этих скафандрах устарели на несколько лет, что отразилось на количестве доступных к установке модулей.

2022-08-22 20:57 UTC, FelineMistress reviewed
еще пара строк

2022-08-24 03:30 UTC, Valtosin commented
проблема в том, что ты поменял `name` у `/datum/mod_theme`. А `name` тут используется для выбора стейта в целом, именно по этой причине я и советую сделать что-то по типу `ru_name` для ВСЕХ тем, оставив при этом оригинальный `name`, чтобы проблема не возникала.

2022-08-24 06:34 UTC, Fesiks commented on code/modules/mod/mod_theme.dm
> +		сложенные в бутерброд для обеспечиваемя инертного слоя, который рассеивает кинетическую энергию в скафандре; \
Встроенные научные очки и детектор взрывов является этим самым массивом

2022-08-24 07:15 UTC, Fesiks commented on code/modules/mod/mod_theme.dm
> +	extended_desc = "Космохонк МУВ-Скафандр был первоначально разработан для межзвездной комедии в условиях низкого юмора. \
в этом же есть доля юмора
Глупые с виду космоклоуны пользуются ультра современными технологиями для своих странных целей

2022-08-25 11:36 UTC, RedFoxIV commented on code/modules/mod/mod_actions.dm
> +	desc = "Открыть панель управления МОД-Скафа."
не ухудшай ситуацию с переводом, пожалуйста - давай вот без этих блятских сокращений
"МОД-Скафандр"

2022-08-25 11:36 UTC, RedFoxIV commented on code/modules/mod/mod_actions.dm
> +	UpdateButtonIcon()
Ты зачем это трогаешь?

2022-08-25 11:40 UTC, RedFoxIV commented on code/modules/mod/mod_activation.dm
> +		balloon_alert(user, "Часть тела одета!")
На пиндоском в два слова всё понятно, на русском прямой перевод звучит как минимум странно.
"На этой части тела уже есть одежда!"

2022-08-25 13:06 UTC, RedFoxIV requested changes
ты инвалид и твоей перевод тоже

![image](https://user-images.githubusercontent.com/38788538/186672729-bb1c0a2c-1ec9-4808-bbd8-9831e26e43fd.png)
вот за это кстати поясни пожалуйста

2022-08-25 13:06 UTC, RedFoxIV commented on code/modules/mod/modules/modules_engineering.dm
> +	desc = "Модуль, использующий отражающие полимеры для защиты пользователя от ионизирующего излучения, \
хули там запятая делает?

"Модуль, использующий отражающие полимеры для защиты пользователя от ионизирующего излучения - обычной опасности в космосе..."

2022-08-25 13:06 UTC, RedFoxIV commented on code/modules/mod/modules/modules_general.dm
> +	desc = "Модуль состоит из серии интегрированных отсеков хранения и специализированные карманов по бокам костюма, для хранения ваших вещей."
специализированных

2022-08-25 13:06 UTC, RedFoxIV commented on code/modules/mod/modules/modules_general.dm
> +		миниатюрные блюспейс карманы для технологии сжимания в точку; независимо от веса объектов, помещенных внутрь."
ты вообще читаешь, что ты пишешь?

"Система хранения, разработанная Нанотразен: эти отсеки используют миниатюрные блуспейс-карманы для ультимативного хранения предметов, вне зависимости от их веса."

2022-08-25 13:06 UTC, RedFoxIV commented on code/modules/mod/modules/modules_ninja.dm
> +	.["statusfingerprints"] = mod.wearer ? md5(mod.wearer.dna.uni_identity) : null
можешь объяснить, нахуя ты это потрогал?

2022-08-25 13:06 UTC, RedFoxIV commented on code/modules/mod/modules/modules_general.dm
> +		заряд от батареи костюма. Некоторые говорят, что это не первая попытка Накамура Инженерия в разработке реактивных ранцев."
имена собственные

2022-08-25 13:08 UTC, RedFoxIV commented
случайно прожал ревью коммита вместо ревью изменённых файлов

похуй, большая часть доёбов вроде должна остаться валидными.

2022-08-25 15:28 UTC, Fesiks commented
> ты инвалид и твоей перевод тоже
> 
> ![image](https://user-images.githubusercontent.com/38788538/186672729-bb1c0a2c-1ec9-4808-bbd8-9831e26e43fd.png) вот за это кстати поясни пожалуйста

Долгая история почему оно тут
Считай пережиток прошлого

2022-08-26 07:34 UTC, Fesiks commented on code/modules/mod/mod_theme.dm
> +		распределения слоев золы или льда по поверхности; эти слои аблативны, но невероятно сильны. \
Там специальный модуль который за ходьбу по пепельной поверхности лаваленда накидывает тебе резистов
Частично оставляю

2022-08-26 20:57 UTC, FelineMistress reviewed
Еще небольшая часть, что то я притомился, опять часов 6 сидел, еще немного осталось

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +	name = "МУВ модуль аппарата для приёма пищи"
модуль для приема пищи

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +	desc = "Любимец шахтеров, эта модификация шлема создаёт нанотехнологический барьер перед ртом \
Лучший выбор для любого шахтера! Позволяет принимать пищу и пить не снимая шлема, \

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +		позволяющий пище и питью проходить, сохраняя защиту и атмосферу. Однако, он не освободит вас от масок, \
благодаря нанотехнологическому барьер перед ртом, без разгерметизации скафандра! Однако вам все еще придется носить кислородную маску, а барьер не защитит \

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +		позволяя перцовому дыму проходить, но даже он не сможет изменить вкус стейка из Голиафа."
от перцовых аэрозолей, и главное он не способен хотя бы на сотую долю улучшить вкусовые качества стейка из Голиафа.

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +		Однако, потребуется заряд скафандра, для защиты."
Однако, энергопотребление скафандра немного увеличится.

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +	name = "МУВ модуль улучшенной защиты от ЭМИ"
продвинутый модуль ЭМИ-защиты

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +		включая аугментации. Однако для этого потребуется дополнительный заряд скафандра."
я не вижу что оно тут делает по сравнению с прошлой моделью, это надо найти и пометить

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +	desc = "Редкая технология, разработанная на основе прототипа, найденного на судне корпорации Донк. \
Донк Ко - без корпорации

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +		Модуль может использовать невероятное количество энергии от батареи скафандра, для создания съедобное органического вещества на \
для синтеза съедобного органического - зачем нам склонения.... нахуй их

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +		ладонь перчаток владельца, однако, разработки полностью остановились на бургерах. \
ладонях -  в жопу склонения

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +	name = "МУВ модуль от падения"
модуль защиты от падения

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +	desc = "Полезный модуль для защиты и костюма и владельца, \
Модуль защищающий носителя от повреждений в случае падения с большой высоты. \

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +		конвертирующий предпологаемый урон от падения в кинетический заряд, \
Часть кинетической энергии полученной в результате падения будет конвертирована в энергию, направленную \

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +		запитывающий внутренние гироскопы энергией для обеспечения безопасного падения пользователя. \
на стабилизацию пользователя. \

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +	to_chat(mod.wearer, span_notice("[src] защищает тебя от падения!"))
Сработала система защиты от падений! - без срц

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +	desc = "Улучшенный климат-контроль, имеет внутреннее покрытие, переплетенное с тысячами крошечных, \
я тебя ебал
Продвинутая система климат-контроля, встроенная в подкладку и использующая тысячи гибких трубочек водяного охлаждения, \

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +		гибких трубок охлаждения. Они обеспечивает циркуляцию охлаждающей жидкости выбранной температуры, \
с выводом температуры на наружные радиаторы. \

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +		обеспечивая комфорт для пользователя, даже окружение обжигает."
Способна поддерживать заданную температуру даже если снаружи бушует плазменный пожар.

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +	desc = "Модуль, который взаимодействует с различными замками и фиксаторами, привязанных к системам костюма, \
склонения идууут нааахер, опяяяять
Модуль блокировки центрального ядра костюма, \

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +		позволяя носить его только тому, кто соответствует точному профилю ДНК пользователя. \
не позволяющий не авторизованному лицу получить доступ без проверки ДНК. \

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +	desc = "Эта система, по сути, переобразует атмосферу, внутри костюма, \
Система атмоформации, преобразующая внутреннюю среду внутри костюма из кислорода в плазму и \

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +		эффективно и быстро предотвращая появления кислорода, вызывающий взрыв плазменной головы пользователя. \
предотвращающая возгорание носителя. \

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +		Это позволяет Плазмаменам, безопасно снимать свой шлем, позволяя более легко \
2 раза позволяет

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +		оснащать оборудованием, относящегося к МОДам, или каким-либо иным образом. \
что тут написано, я не понимаю как? блять я устал, просто стирай этот кусок я даже придумывать не хочу ничего

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +		Фиолетовое стекло шлема, кажется, создано только для ностальгических целей."
когда кажется креститься надо, воткул в середину зачем то, все внимание на него уходит, предложение надвое располовинил - хотя и оригинал бредовый 
Плазмастекло предотвращает ионизацию плазмы

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +		base_examine += span_notice("Тут установленна на шлеме [attached_hat]. Правый-клик для снятия.")
На шлеме закреплена [attached_hat]

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +		base_examine += span_notice("Тут ничего не установленно. Пока-что.")
Ничего не закреплено

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +		balloon_alert(user, "Шляпа уже установленна!")
закреплена

2022-08-26 20:57 UTC, FelineMistress commented on code/modules/mod/modules/modules_general.dm
> +		balloon_alert(user, "Шляпа установленна. Правый-клик для снятия")
закреплена

2022-08-29 21:18 UTC, FelineMistress reviewed
Завтра с утра доделаю, немного осталось

2022-08-29 21:18 UTC, FelineMistress commented on code/modules/mod/modules/modules_supply.dm
> +	desc = "Этот модуль использует обычную технологию Нанотрэйзен для вычисления положения пользователя в любом месте пространства, \
Стандартный GPS-модуль не изменивший свой функционал с 21 века. В большинстве случаев используется для отслеживания местоположения, как своего, так и окружающих сигналов.

2022-08-29 21:18 UTC, FelineMistress commented on code/modules/mod/modules/modules_supply.dm
> +	desc = "Серия приводов, установленных в обе руки скафандра, с грузоподъемностью почти тонну. \
почти в тонну

2022-08-29 21:18 UTC, FelineMistress commented on code/modules/mod/modules/modules_supply.dm
> +		Тем не менее, эта конструкция была блокирована от переноски чего то отличного от ящиков. \
Однако модель захватов поддерживает исключительно крепеж стандартных грузовых ящиков. \

2022-08-29 21:18 UTC, FelineMistress commented on code/modules/mod/modules/modules_supply.dm
> +		Многие скажут, что погрузка груза - скучная работа, но вы больше не можете так думать."
погрузка груза - масло масляное - ищи синонимы - ДУМАЙ
вы с ними не согласитесь

2022-08-29 21:18 UTC, FelineMistress commented on code/modules/mod/modules/modules_supply.dm
> +		balloon_alert(mod.wearer, "Поднял [picked_crate]")
Поднимаю

2022-08-29 21:18 UTC, FelineMistress commented on code/modules/mod/modules/modules_supply.dm
> +		balloon_alert(mod.wearer, "Сбросил [dropped_crate]")
Опускаю

2022-08-29 21:18 UTC, FelineMistress commented on code/modules/mod/modules/modules_supply.dm
> +	name = "модуль гидравлического загрузчика"
почему у карго скафандра одно, у модуля другое, сам предмет третье название имеет

2022-08-29 21:18 UTC, FelineMistress commented on code/modules/mod/modules/modules_supply.dm
> +		Компания Накамура Инжинирия рекомендует, разгружать руду в местные шахтёрские печи."
Данная конструкция является заслуженной гордостью компании Накамура Инжиниринг.

2022-08-29 21:18 UTC, FelineMistress commented on code/modules/mod/modules/modules_supply.dm
> +	name = "модуль пометки назначения" //стопроцентов что я не понял что это за модуль
модуль этикеровщика назначения

2022-08-29 21:18 UTC, FelineMistress commented on code/modules/mod/modules/modules_supply.dm
> +	name = "модуль сбора пепла"
модуль пепельной защиты

2022-08-29 21:18 UTC, FelineMistress commented on code/modules/mod/modules/modules_supply.dm
> +	desc = "Модуль, который собирает пепел с местности, покрывая костюм защитным слоем, этот слой \
Модуль, собирающий пепельную взвесь с окружающей местности и покрывающий скафандр  дополнительным защитным слоем. Пепельная защита со временем спадает.

2022-08-29 21:18 UTC, FelineMistress commented on code/modules/mod/modules/modules_supply.dm
>  			balloon_alert(mod.wearer, "ran out of ash!")
Пепел закончился!

2022-08-29 21:18 UTC, FelineMistress commented on code/modules/mod/modules/modules_supply.dm
> +		balloon_alert(mod.wearer, "Слишком много давления!")
Слишком высокое давление!

2022-08-30 12:36 UTC, FelineMistress reviewed
Ну первичная вычитка все, теперь убирать ошибки, в первую очередь name_ru как Валера сказал

2022-08-30 12:36 UTC, FelineMistress commented on code/modules/mod/modules/modules_timeline.dm
> +	name = "модуль временной блокировки"
у нас они пока вырезаны так что временно отложим. пусть есть как есть

2022-08-30 12:36 UTC, FelineMistress commented on code/modules/mod/modules/modules_visor.dm
> +	name = "МУВ модуль визора" // Я ЗАБЫЛ КАК ХУД ПЕРЕВОДИТСЯ
Heads-Up Display, аббр. HUD — часть визуального интерфейса игрока, отображающаяся на переднем плане виртуального игрового пространства в видеоигре. [ru.wikipedia.org]
но мы так и оставляем HUD потому что расшифровывать его не обязательно, все понимают о чем речь, но визор нормально  звучит, так что пусть будет визор

2022-08-30 12:36 UTC, FelineMistress commented on code/modules/mod/modules/modules_visor.dm
> +	name = "МУВ модуль медицинского визора"
без  МУВ - тут и далее

2022-08-30 12:36 UTC, FelineMistress commented on code/modules/mod/modules/modules_visor.dm
> +	desc = "В шлем скафандра встраивается дисплей. Этот перекрёсный сканер получает доступ к данным датчика с современных \
Встраиваемый в шлем медицинский HUD-интерфейс позволяет пользователю визуализировать текущее состояние органических форм жизни, ...

2022-08-30 12:36 UTC, FelineMistress commented on code/modules/mod/modules/modules_visor.dm
> +		доступ к данным, таким как файлы пациентов в удобной для считывания виде.  Говорят, он также позволяет видеть сзади."
видеть сзади лучше убрать - у нас нет ФОВа, этот прикол тупо не понятен у нас

2022-08-30 12:36 UTC, FelineMistress commented on code/modules/mod/modules/modules_visor.dm
> +	name = "МУВ диагностирующего визора"
модуль диагностического визора

2022-08-30 12:36 UTC, FelineMistress commented on code/modules/mod/modules/modules_visor.dm
> +	desc = "В шлем скафандра встраивается дисплей. Для доступа к данным используется ряд усовершенствованных датчиков \
оформить так же как медицинский

2022-08-30 12:36 UTC, FelineMistress commented on code/modules/mod/modules/modules_visor.dm
> +	desc = "В шлем скафандра встраивается дисплей. Этот модуль представляет собой сильно модифицированную систему наведения, \
см выше, ну и те что ниже покрасивше начало надо первое предложение у всех, середина нормально, в конце убрать прикол про ФОВ

2022-08-30 12:36 UTC, FelineMistress commented on tgui/packages/tgui/interfaces/MODsuit.js
> +          title="Уровень опасности"
Уровень заражения

2022-08-30 12:36 UTC, FelineMistress commented on tgui/packages/tgui/interfaces/MODsuit.js
> +          <Section title="Удушение">
Удушье

2022-08-30 12:36 UTC, FelineMistress commented on tgui/packages/tgui/interfaces/MODsuit.js
> +          <Section title="Удушение">
Удушье

2022-08-30 12:36 UTC, FelineMistress commented on tgui/packages/tgui/interfaces/MODsuit.js
> +          <LabeledList.Item label="Уникальные ферменты">
оставляем Энзимы

2022-08-30 12:36 UTC, FelineMistress commented on tgui/packages/tgui/interfaces/MODsuit.js
> +          СКАФНДР БЕЗ ПИТАНИЯ
ОБЕСТОЧЕН

2022-08-30 12:36 UTC, FelineMistress commented on tgui/packages/tgui/interfaces/MODsuit.js
> +      return 'Использовать';
я не очень понимаю что это надо проверить работоспособность

2022-08-30 12:36 UTC, FelineMistress commented on tgui/packages/tgui/interfaces/MODsuit.js
>              {gauntlets || 'None'}
Нет

2022-08-30 12:36 UTC, FelineMistress commented on tgui/packages/tgui/interfaces/MODsuit.js
> +          <LabeledList.Item label="Ботинки">{boots || 'нет'}</LabeledList.Item>
раз все начал с большой буквы то и тут

2022-08-30 12:36 UTC, FelineMistress commented on tgui/packages/tgui/interfaces/MODsuit.js
> +          })) || <Box textAlign="center">Нет информационных модулев</Box>}
модулей

2022-08-30 12:36 UTC, FelineMistress commented on tgui/packages/tgui/interfaces/MODsuit.js
> +                            tooltip="Сложность"
Нагрузка на систему

2022-08-30 12:36 UTC, FelineMistress commented on tgui/packages/tgui/interfaces/MODsuit.js
> +                            tooltip="Потреблении в активе"
Активное потребление

2022-08-30 12:36 UTC, FelineMistress commented on tgui/packages/tgui/interfaces/MODsuit.js
> +                            tooltip="Потребление в простое"
Пассивное потребление

2022-08-30 12:36 UTC, FelineMistress commented on tgui/packages/tgui/interfaces/MODsuit.js
> +                            tooltip="Стоимость использования"
Потребление при активации

2022-09-01 10:21 UTC, Valtosin commented
сделай имена тем на АНГЛИЙСКОМ, на тебя ругается хуйня

2022-09-01 10:39 UTC, Fesiks commented
> сделай имена тем на АНГЛИЙСКОМ, на тебя ругается хуйня

Так сделал уже
Как ты и сказал
Name на инглише и добавить ру нейм на русском

2022-09-04 22:12 UTC, Valtosin commented
> Так сделал уже Как ты и сказал Name на инглише и добавить ру нейм на русском

для ВСЕХ тем надо. Она же не одна

в любом случае конфликты не фикси пока, через недельку замержим правильно

2022-09-07 18:07 UTC, merged