MagiiNet.com
frosty-dev/white pull request #1381
Opened 2022-08-30 09:55 UTC by GrishaGold

Перевод магии. (В процессе)

2022-08-31 16:13 UTC, FelineMistress commented on code/modules/antagonists/wizard/equipment/spellbook_entries/defensive.dm
> +	desc = "Посох, который стреляет снарядом. Который съедает всех, кого встречает на своем пути, оставляя за собой сварной шкафчик с вашими жертвами."
Мистический посох, снаряды которого замуровывают своих жертв в запертых волшебных шкафчиках.

2022-08-31 16:13 UTC, FelineMistress commented on code/modules/antagonists/wizard/equipment/spellbook_entries/defensive.dm
> +	desc = "Раскаленный шар потрескивающей энергии. Использование его позволит вам выпустить своего призрака при жизни, что позволит вам шпионить за станцией и разговаривать с умершим. Кроме того, его п
скопируй описание из самого предмета, там вроде неплохое, его переводили ранее

2022-08-31 16:13 UTC, FelineMistress commented on code/modules/antagonists/wizard/equipment/spellbook_entries/defensive.dm
> +	name = "Асортимент палочек"
Перевязь для посохов

2022-08-31 16:13 UTC, FelineMistress commented on code/modules/antagonists/wizard/equipment/spellbook_entries/defensive.dm
> +	desc = "Коллекция палочек, которые обеспечивают широкий спектр полезности. \
Набор разнообразных посохов на все случаи жизни. \

2022-08-31 16:13 UTC, FelineMistress commented on code/modules/antagonists/wizard/equipment/spellbook_entries/defensive.dm
> +		Палочки имеют ограниченное количество зарядов, поэтому будьте осторожны в их использовании. Поставляется в удобном ремне."
Посохи
Поставляются с удобной перевязью для хранения

2022-08-31 16:13 UTC, FelineMistress commented on code/modules/antagonists/wizard/equipment/spellbook_entries/defensive.dm
> +	to_chat(user, span_notice("[to_equip.name] был вызван [was_equipped ? "в твоих руках" : "у твоих ног"]."))
моих

2022-08-31 16:13 UTC, FelineMistress commented on code/modules/antagonists/wizard/equipment/spellbook_entries/defensive.dm
> +	name = "Набор Доспехов Боевого Мага"
Комплект

2022-08-31 16:13 UTC, FelineMistress commented on code/modules/antagonists/wizard/equipment/spellbook_entries/defensive.dm
> +	desc = "Артефактный доспех, который позволяет вам произносить заклинания \
Артефакторный доспех, помогающий при чтении заклинаний и \

2022-08-31 16:13 UTC, FelineMistress commented on code/modules/antagonists/wizard/equipment/spellbook_entries/defensive.dm
> +		обеспечивая при этом большую защиту от атак и космоса. \
обеспечивающий высокую защиту от всех видов урона и космического вакуума. \

2022-08-31 16:13 UTC, FelineMistress commented on code/modules/antagonists/wizard/equipment/spellbook_entries/defensive.dm
> +		Также дает щит боевого мага."
дарует

2022-08-31 16:13 UTC, FelineMistress commented on code/modules/antagonists/wizard/equipment/spellbook_entries/defensive.dm
> +	name = "Заряды брони Боевого Мага"
Накопитель для доспехов боевого мага

2022-08-31 16:13 UTC, FelineMistress commented on code/modules/antagonists/wizard/equipment/spellbook_entries/defensive.dm
> +	desc = "Мощный защитный оберег, он даст восемь дополнительных зарядов щиту боевого мага.."
дарующий восемь дополнительных зарядов для доспехов боевого мага

2022-09-02 16:48 UTC, RedFoxIV requested changes

2022-09-02 16:48 UTC, RedFoxIV commented on code/modules/antagonists/wizard/equipment/spellbook_entries/_entry.dm
> +		log_spellbook("[key_name(user)] улучшил свои знания о [initial(existing.name)] до следующего уровня [existing.spell_level] за [cost] очков")
логи не переводить

2022-09-02 16:48 UTC, RedFoxIV commented on code/modules/antagonists/wizard/equipment/spellbook_entries/_entry.dm
> +	log_spellbook("[key_name(user)] выучил [new_spell] за [cost] очков")
логи не переводить

2022-09-02 16:48 UTC, RedFoxIV commented on code/modules/antagonists/wizard/equipment/spellbook_entries/_entry.dm
> +	to_chat(user, span_notice("[to_equip.name] был вызван [was_put_in_hands ? "в моих руках" : "у моих ног"]."))
"был вызван и оказался"
Был вызван в моих руках звучит, как минимум, странно.

2022-09-02 16:48 UTC, RedFoxIV commented on code/modules/antagonists/wizard/equipment/spellbook_entries/_entry.dm
> +	log_spellbook("[key_name(user)] совершает [src] за [cost] очков")
логи

2022-09-02 16:48 UTC, RedFoxIV commented on code/modules/antagonists/wizard/equipment/spellbook_entries/assistance.dm
> +	desc = "Это заклинание можно использовать для подзарядки самых разных вещей в ваших руках, от магических артефактов до энергозависимой экипировки. Творческий волшебник может даже использовать его, ч
Креативный волшебник
Творческий тут неуместно

2022-09-02 16:48 UTC, RedFoxIV commented on code/modules/antagonists/wizard/equipment/spellbook_entries/assistance.dm
> +	desc = "Магический контракт, обязывающий ученика школы волшебства служить вам, его использование вызовет его к вам."
ТГшники дебилы, можно добавить строчку про возврат средств если нету гостов

2022-09-02 16:48 UTC, RedFoxIV commented on code/modules/antagonists/wizard/equipment/spellbook_entries/defensive.dm
> +	desc = "Темный некромантический договор, который может навсегда запечатать вашу душу в предмет который вы держите в руках, \
"некромантический" звучит косноязычно

2022-09-02 16:48 UTC, RedFoxIV commented on code/modules/antagonists/wizard/equipment/spellbook_entries/defensive.dm
> +	name = "Ослабленный Призыв Пчёл"
Малый

2022-09-02 18:50 UTC, merged