Костюм сола гудмана
frosty-dev/white pull request #1440
Opened 2022-09-17 14:22 UTC by SuprGmr

Костюм Сола гудмана, при надевании делает тууууууун пам пам пам пам, пам пампампам

2022-09-17 14:29 UTC, RedFoxIV requested changes
чё думал так легко будет?

2022-09-17 14:29 UTC, RedFoxIV commented on white/BrmTinke/code/saul_gnom.dm
> +	desc = "Костюм человека закончившего юридический университет"
запятую перед закончившего добавь

2022-09-17 14:29 UTC, RedFoxIV commented on white/BrmTinke/code/saul_gnom.dm
> +	name = "Очень деловой костюм"
имена предметов со строчной

2022-09-17 14:29 UTC, RedFoxIV commented on white/BrmTinke/code/saul_gnom.dm
> +
нахуй тут 20+ пустых строк?

2022-09-17 14:32 UTC, SuprGmr commented on white/BrmTinke/code/saul_gnom.dm
> +	desc = "Костюм человека закончившего юридический университет"
Я в первом классе учусь

2022-09-17 17:05 UTC, RedFoxIV approved these changes
пойдёт

2022-09-21 16:59 UTC, FelineMistress commented on code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
> +	desc = "Шахтер, обреченный на вечные скитания, занятый бесконечной охотой..."
занятый > помешанный / проклятый / зацикленный на - предложение согласовать

2022-09-21 16:59 UTC, FelineMistress commented on code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
> +	desc = "Монструозное создание, обладающее тяжёлой защитой"
точка

2022-09-21 16:59 UTC, FelineMistress commented on code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
> +	name = "аномальный кристал"
кристалл

2022-09-21 16:59 UTC, FelineMistress commented on code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
> +	desc = "Странный кристал, в его присутствии ваша душа наполняется волнением и ужасом."
кристалл

2022-09-21 16:59 UTC, FelineMistress commented on code/modules/mob/living/simple_animal/hostile/megafauna/demonic_frost_miner.dm
> +	desc = "Тяжеловооружённый шахтёр. Сошедший с ума или одержимый демонами, он всё равно остаётся опасным врагом"
но тем не менее

2022-09-21 16:59 UTC, FelineMistress commented on code/modules/mob/living/simple_animal/hostile/megafauna/demonic_frost_miner.dm
> +	visible_message(span_danger("[src] поглощает взрыв!"), span_userdanger("Вы поглощаете взрыв!"))
от первого лица без Вы "Сдерживаю ударную волну!"

2022-09-21 16:59 UTC, FelineMistress commented on code/modules/mob/living/simple_animal/hostile/megafauna/demonic_frost_miner.dm
> +	desc = "Светящаяся хуйня, которая была при шахтёре, но по какой-то причине он не смог ее использовать.."
следим за речью
Светящийся медальон 
согласовать предложение
лишняя точка

2022-09-21 16:59 UTC, FelineMistress commented on code/modules/mob/living/simple_animal/hostile/megafauna/demonic_frost_miner.dm
> +	desc = "Ты заморожен во льду, и не можешь двигаться!"
Меня заморозили во льду! Я не могу двинуться!

2022-09-21 16:59 UTC, FelineMistress commented on code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
> +	name = "\improper Страж легиона"
\improper всегда и везде удаляем

2022-09-21 16:59 UTC, FelineMistress commented on code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
> +	desc = "Взгляд пронзает твою душу."
Его взгляд прознает саму душу.

2022-09-21 16:59 UTC, FelineMistress commented on code/modules/mob/living/simple_animal/hostile/megafauna/swarmer.dm
> +	desc = "Это название немного многословное, но перестаньте обращать внимание на это, они не любят говорить!"
Это описание больше не подходит, оно описывало игру слов на англ.
"Чужеродное устройство, занимающееся постоянной репликацией дронов, единственная цель которых это сбор ресурсов, в бесконечных объемах, любой ценой."

2022-09-21 17:32 UTC, closed without merging