Sanecman sral 1 FIXED VERSION FREE TO DOWNLOAD 2022 EDITION
frosty-dev/white pull request #1563
Opened 2022-10-18 11:14 UTC by SanecMan

```diff
+ Перевод халф лайв в гейтвее // Перевод готов на 100%
+ Фикс захода в актёрку до начала раунда // Любители убивать себя до начала раунда а потом дрочить в гостоте хуй тут?
+ Теперь можно выдавать баны на вход в игру // Доступ в раунд через НАБЛЮДАТЬ и ПРИСОЕДЕНИТЬСЯ недоступен, только ОБУЧЕНИЕ
```
Возможно ещё что-то во время проверки фелином, так что как ТОЧНО всё будет проверено и утверждено можно будет мержить. 

https://user-images.githubusercontent.com/36476150/196414589-642d5906-a135-4912-bbe2-926353cddc99.mp4

2022-10-18 11:29 UTC, FelineMistress commented
Зоны так и не исправлены, все еще есть опечатки, создавать новый ПР это не очень практично, ведь пометки были на старом, но хозяин-барин если удобно с паралелью делать - делай

2022-10-18 11:33 UTC, GrishaGold commented
![image0.gif](https://user-images.githubusercontent.com/91083635/196418408-9dd01aee-897a-47d0-8eaa-0e5794154680.gif)

2022-10-18 11:36 UTC, SanecMan commented
> Зоны так и не исправлены, все еще есть опечатки, создавать новый ПР это не очень практично, ведь пометки были на старом, но хозяин-барин если удобно с паралелью делать - делай

@FelineMistress я твою маму любил и при обновлении с апстрима мне насрало кучей ошибок, так что решил почистить ветку ну и пр закрылся, вот





Специально для @GrishaGold фелину и другим не открывать

https://user-images.githubusercontent.com/36476150/196418824-f7f24b48-81f4-4170-95c1-5b4e22d5cdde.mp4

2022-10-18 11:39 UTC, GrishaGold commented
![photo5291807563517635672.jpg](https://user-images.githubusercontent.com/91083635/196419533-51f3a3ec-6a32-487b-bcdc-96bbc6d4495c.jpg)

2022-10-18 11:40 UTC, SanecMan commented
@GrishaGold узнал себя? сосал?

2022-10-18 11:43 UTC, GrishaGold commented
Ржака. Исправляй ошибки.

2022-10-18 11:44 UTC, SanecMan commented
> Ржака. Исправляй ошибки.

моя ошибка в том что ты срёшь сюда а не должен

2022-10-18 11:47 UTC, FelineMistress commented
Возьми себя в руки и спокойно работай, не назло, и не с похуизмом, а так чтобы не позориться. Тебе указали на ошибки, ты исправил пятую часть и решил что устал и остальное и так сойдет. Не прокатило - разверещался с грязными оскорблениями кидая какие-то ссылки которые почему-то играли против тебя же. Такая детская истерика что ты устроил в баре и блок-канале это не по мужски. У взрослого человека она вызывает лишь брезгливое отторжение, никого вывести из себя ты так не сможешь, только сам будешь себя больше топить. Единственное как ты можешь меня задеть это продолжить дальше позориться с забиванием болта, я как ответственный человек к сожалению буду это вычитывать. Но даже так я просто в конце тоже забью болт и буду отклонять. Сделай нам одолжение не надо что-то кому-то доказывать - не нравится этим заниматься - так и скажи, всем будет проще. Хочешь заниматься - относись к этому по взрослому.

2022-10-18 11:49 UTC, SanecMan commented
@FelineMistress лан нигер

2022-10-19 04:25 UTC, Valtosin commented
сниму смайт как вмержим

2022-10-19 04:29 UTC, Valtosin requested changes
пук

2022-10-19 04:29 UTC, Valtosin commented on white/RedFoxIV/code/obj/weapons/misc.dm
> +			if(!SSticker?.IsRoundInProgress())
это плохой фикс, так как сами артисты были впилены в лобби в качестве разминки перед началом раунда. Придумай чет другое

2022-10-19 04:33 UTC, SanecMan commented on white/RedFoxIV/code/obj/weapons/misc.dm
> +			if(!SSticker?.IsRoundInProgress())
Можно сделать отдельную комнату как на очень старом тг или как на Инфинити но мне впадлу ебаться и придумывать всё так что похуй чето сделаю придумаю.
![IMG_20221018_110704_590.jpg](https://user-images.githubusercontent.com/36476150/196598286-9ec4d304-91c8-4d2d-8497-ca1da6631327.jpg)

2022-10-19 05:09 UTC, Valtosin commented on white/RedFoxIV/code/obj/weapons/misc.dm
> +			if(!SSticker?.IsRoundInProgress())
там изначальная проблема была в том, что человеки не возвращались в лобби после крита

2022-10-19 05:45 UTC, SanecMan commented on white/RedFoxIV/code/obj/weapons/misc.dm
> +			if(!SSticker?.IsRoundInProgress())
Ну есть код обучения где человеки возвращаются в лобби, чё бы его не использовать?

2022-10-19 05:49 UTC, SanecMan commented on white/RedFoxIV/code/obj/weapons/misc.dm
> +			if(!SSticker?.IsRoundInProgress())
Или ты про то что ОБУЧЕНИЕ перед началом раунда не возвращает в лобби? Если ты про это то тут хз как фиксить ибо эта хуйня работает странно. Например если умереть за артиста то твое тело до начала раунда не превратится в пыль а лишь после. Короче как сделал так и сделал по другому никак не знаю. Хотя можно конечно сделать что-то с помощью трейтов но я подумаю как это реализовать.

2022-10-19 07:30 UTC, FelineMistress commented on white/valtos/code/black_mesa/armor.dm
> +	name = "керамический жилет"
бронежилет

2022-10-19 07:30 UTC, FelineMistress commented on white/valtos/code/black_mesa/follow_component.dm
> +	examine_text += "Alt-click заставит идти за собой!"
Alt-клик

2022-10-19 07:30 UTC, FelineMistress commented on white/valtos/code/black_mesa/hev_suit.dm
> +			send_message("ПРОТИВОТОКСИННОЕ ВЕЩЕСТВО ВВЕДЕНО", HEV_COLOR_BLUE)
Такого слова нет, но пофиг уже

2022-10-19 07:30 UTC, FelineMistress commented on white/valtos/code/black_mesa/hev_suit.dm
> +			send_message("ПРОТИВОРАЗЛАГАЕМОЕ ВЕЩЕСТВО ВВЕДЕНО", HEV_COLOR_BLUE)
Ну я же писал это не разложение это cloneloss - клеточный урон, да он очень редкий, но разложение это процесс у трупа, а не у живого. Давай подумаем что тут можно написать. Можно "клеточный стабилизатор введен", но это не подходит под выбранную стилистику, можно "стволовые клетки введены", не знаю что придумать такое чтобы там было слово вещество, ну или можно "экспериментальное вещество введено"

2022-10-19 07:30 UTC, FelineMistress commented on white/valtos/code/black_mesa/mobs/gordon_freeman.dm
> +	name = "ИД карта Фримена"
лучше оставлять "ID" на англ, я пробовал писать "ИД" - не понимают и путаются, да и плохо смотрится

2022-10-19 07:30 UTC, FelineMistress commented on white/valtos/code/black_mesa/uber_teleporter.dm
> +	name = "его владения"
измерение/владения Нихиланта, если так хочешь использовать местоимение, то тогда оно должно быть с большой буквы и в кавычках, кавычки ставятся через \

2022-10-19 07:30 UTC, FelineMistress commented on white/valtos/code/black_mesa/weapons.dm
> +	desc = "Оружие, которым владел один известный физик, кровь сотен людей просачивается сквозь этот стержень из железа и злобы."
я бы все же заменил людей на созданий или существ. Это дело вкуса, но ведь Фримен сражается с монстрами в первую очередь, это уже потом Альянс, Комбайны все дела, ну если так хочешь оставь

2022-10-19 07:30 UTC, FelineMistress commented on white/valtos/code/black_mesa/xen_crystal.dm
> +		to_chat(user, span_warning("С [src] уже отломили кусок!"))
я знаю что редфокс такое не любит, но в таких случаях проще удалить [src] и написать в правильном склонении сразу, да есть хелперы которые будут склонять, но проще исправить тут чем я буду объяснять как их использовать. В противном случае будет "С кристалл уже отломили кусок!"

2022-10-19 07:35 UTC, SanecMan commented on white/valtos/code/black_mesa/armaments/armament_component.dm
> +		to_chat(user, span_warning("Лимит категорий достигнут!"))
А чё написать

2022-10-19 17:06 UTC, yafacepravda2 commented on white/valtos/code/black_mesa/armaments/armament_component.dm
> +		to_chat(user, span_warning("Лимит категорий достигнут!"))
> Ну наверное "лимит категории" через "и" если "й" то имеется ввиду что больше нет категорий, а если "и", то типо все - больше покупать нельзя

интересно

2022-10-19 17:59 UTC, RedFoxIV requested changes
>+ Теперь можно выдавать баны на вход в игру // Доступ в раунд через НАБЛЮДАТЬ и ПРИСОЕДЕНИТЬСЯ недоступен, только ОБУЧЕНИЕ

Не нужно. Вырезай.

2022-10-19 17:59 UTC, RedFoxIV commented on code/_onclick/hud/new_player.dm
> +	if(is_banned_from(new_player.ckey, "Join and Observe"))
Это чё

2022-10-19 18:00 UTC, RedFoxIV commented on white/valtos/code/black_mesa/xen_crystal.dm
> +		to_chat(user, span_warning("С [src] уже отломили кусок!"))
Я вообще думаю, чтобы захуярить сразу в /datum какой-нибуть список со всеми склонениями в единственном и множественном числах, чтобы не было больше всяких железноей стержненей

2022-10-19 18:01 UTC, RedFoxIV commented on white/valtos/code/black_mesa/hev_suit.dm
> +			send_message("ПРОТИВОРАЗЛАГАЕМОЕ ВЕЩЕСТВО ВВЕДЕНО", HEV_COLOR_BLUE)
>MEDICAL ATTNETION
отсебятина, переводи нормально

2022-10-20 10:34 UTC, FelineMistress commented
ну сторону перевода с поправками я условно принимаю, теперь развлекайся с Фоксом и Валерой

2022-10-20 11:21 UTC, RedFoxIV commented
Не вижу исправлений говняка. Как будет, открою.

2022-10-20 11:21 UTC, closed without merging

2022-10-20 12:35 UTC, SanecMan commented
сука я только сел работать

2022-10-21 10:35 UTC, Valtosin commented
@RedFoxIV в закрытый пуллреквест не отправляются изменения из форка

2022-10-21 10:35 UTC, Valtosin commented
или я в глаза ебусь

2022-10-21 11:58 UTC, SanecMan commented
Редфокс сломал пр https://user-images.githubusercontent.com/36476150/197190603-14176efe-df27-4777-bed9-ca7c32a474d8.mp4

2022-10-21 16:06 UTC, FelineMistress commented
отправляются при его переоткрытии, я со своими так делаю если мне срет ошибками