Ура ура, мама я кодер (Очки O.S.I. за метакеш)
frosty-dev/white pull request #1573
Opened 2022-10-20 21:45 UTC by Nikitauou

😎

2022-10-20 21:47 UTC, Nikitauou commented
Тут чёт 98 и 104 строчку задело, не уверен что я всё правильно сделал

2022-10-20 23:34 UTC, SanecMan commented on white/valtos/code/loadout/loadout_accessories.dm
> +	cost = 150
давай больше цену а то ща все начнут покупать их

2022-10-20 23:45 UTC, Nikitauou commented on white/valtos/code/loadout/loadout_accessories.dm
> +	cost = 150
Так это обычные очки за 250 кредитов +- в раздатчике одежды

2022-10-21 04:15 UTC, Valtosin requested changes

2022-10-21 04:15 UTC, Valtosin commented on white/valtos/code/loadout/loadout_accessories.dm
> +	allowed_roles = list("Cargo Technician")
hello нахуя

2022-10-21 08:03 UTC, Nikitauou commented on white/valtos/code/loadout/loadout_accessories.dm
> +	allowed_roles = list("Cargo Technician")
Да я сам не понял насчёт этих 2х строчек, вроде их не менял

2022-10-21 09:20 UTC, FelineMistress commented
Надеюсь они не предоставляют защиту от вспышек, я просто не помню что это за очеи

2022-10-21 09:21 UTC, Nikitauou commented
Это самые обычные очки из вендомата одежды

2022-10-21 09:21 UTC, FelineMistress commented
Ну пофиг тогда, чего нет

2022-10-21 09:22 UTC, FelineMistress commented
Просто отмени изменения у карготеха и все норм

2022-10-21 09:24 UTC, Nikitauou commented
Да вроде валтос уже всё сделал

2022-10-21 09:28 UTC, FelineMistress commented
Нет, я не вижу комитов с изменениями, он просто это прокомментировал

2022-10-21 09:45 UTC, merged