Kayf Life 2
frosty-dev/white pull request #1592
Opened 2022-10-23 11:36 UTC by SanecMan

хотел сначала полностью звуки перенести из русской локализации Half Life в билд, но @FelineMistress решил что нахуй надо, так что вот вам правки локализации.

2022-10-23 12:02 UTC, RedFoxIV requested changes
![image](https://user-images.githubusercontent.com/38788538/197391000-81a4dfd5-0300-4164-9946-741a84fcbf22.png)
не вижу фикса вот этой хуйни

2022-10-23 12:02 UTC, RedFoxIV commented on README.md
> +-->
![image](https://user-images.githubusercontent.com/38788538/197390942-d5de15ef-7a0d-4e50-ab4a-b51585f815cd.png)

2022-10-23 12:04 UTC, SanecMan commented
> ![image](https://user-images.githubusercontent.com/38788538/197391000-81a4dfd5-0300-4164-9946-741a84fcbf22.png) не вижу фикса вот этой хуйни

и чё тут фиксить то

2022-10-23 12:07 UTC, RedFoxIV commented
> и чё тут фиксить то
![исходник (2)](https://user-images.githubusercontent.com/38788538/197391210-d8d817a7-6356-47cd-a3b3-1e36e7e62f69.png)

2022-10-23 12:12 UTC, RedFoxIV commented on white/valtos/code/black_mesa/mobs/headcrab_zombie.dm
> +	desc = "Исследователь на котором надет костюм биологической защиты H.E.V."
запятую проебал.
А ещё про биологическую защиту не уместно, это защитный костюм общего назначения
либо так, либо убери

2022-10-23 12:47 UTC, RedFoxIV commented
костюм защитный костюм

2022-10-23 12:47 UTC, RedFoxIV commented
жду филина

2022-10-23 12:51 UTC, SanecMan commented
https://user-images.githubusercontent.com/36476150/197393104-087a4042-cebc-45e8-ab13-8c37ff2bd0ab.mp4

2022-10-23 14:46 UTC, FelineMistress commented on white/valtos/code/black_mesa/mobs/headcrab_zombie.dm
> +	name = "зомбированый учёный"
зомбированный, странно что в первый раз ты написал правильно, а потом 3 раза подряд неправильно, видимо в первый раз было копирование с переводчика

2022-10-23 14:47 UTC, FelineMistress commented
> > ![image](https://user-images.githubusercontent.com/38788538/197391000-81a4dfd5-0300-4164-9946-741a84fcbf22.png) не вижу фикса вот этой хуйни
> 
> и чё тут фиксить то

2 раза слово "костюм" в одном предложении, речевая ошибка

2022-10-23 14:48 UTC, SanecMan commented
> > > ![image](https://user-images.githubusercontent.com/38788538/197391000-81a4dfd5-0300-4164-9946-741a84fcbf22.png) не вижу фикса вот этой хуйни
> > 
> > 
> > и чё тут фиксить то
> 
> 2 раза слово "костюм" в одном предложении, речевая ошибка

Тест полностью переписан

2022-10-23 14:49 UTC, SanecMan commented on white/valtos/code/black_mesa/mobs/headcrab_zombie.dm
> +	name = "зомбированый учёный"
![image](https://user-images.githubusercontent.com/36476150/197398916-2fad6261-8584-4367-9590-ac3cd561b746.png)

2022-10-23 14:58 UTC, FelineMistress commented
топаешь вот сюда и смотришь какие там были пометки, там не много, но ты их не исправил: вакуум, модульный шлем, ПРОТИВОРАЗЛАГАЕМОЕ,  https://github.com/frosty-dev/white/pull/1563

2022-10-23 15:04 UTC, SanecMan commented
> топаешь вот сюда #1563 и смотришь какие там были пометки, там не много, но ты их не исправил: вакуум, модульный шлем, ПРОТИВОРАЗЛАГАЕМОЕ. Я просто уже не хочу в 3 раз для тебя это выискивать, я 2 раза уже показал

займусь на днях ЕСЛИ этот ПР снова не закроет редфокс

2022-10-24 08:10 UTC, RedFoxIV requested changes

2022-10-24 08:10 UTC, RedFoxIV commented on white/valtos/code/black_mesa/armaments/__armament_bodyarmor.dm
> +	desc = "Содержит энергетический боевой шлем и жилет марк II"
переписать
![image](https://user-images.githubusercontent.com/38788538/197478544-e56347f6-bb5a-4911-9a25-e5e2f79a85f2.png)

2022-10-24 08:11 UTC, SanecMan commented on white/valtos/code/black_mesa/armaments/__armament_bodyarmor.dm
> +	desc = "Содержит энергетический боевой шлем и жилет марк II"
напиши как и я перепишу нигер хуесос гнида мудило членосос пидорас

2022-10-24 08:13 UTC, FelineMistress commented on white/valtos/code/black_mesa/armaments/__armament_bodyarmor.dm
> +	desc = "Содержит энергетический боевой шлем и жилет марк II"
Да вроде нормально? Я напомню что "Марк" это номенклатурное обозначение, аналогичное нашей "Модель" или "Тип", ну если с большой буквы только, но это совершенно не принципиально

2022-10-24 08:15 UTC, SanecMan commented on white/valtos/code/black_mesa/armaments/__armament_bodyarmor.dm
> +	desc = "Содержит энергетический боевой шлем и жилет марк II"
"Содержит комплект ЭБЖ марк II" устроит?

2022-10-24 08:39 UTC, FelineMistress commented
Саша, иди с богом, все, ты молодец

2022-10-24 08:46 UTC, FelineMistress commented
Хочу 2 НН

2022-10-24 08:51 UTC, FelineMistress commented
умница, я тобой горжусь! Пусть все знают! Саня СМОГ!

2022-10-24 08:51 UTC, merged

2022-10-24 08:51 UTC, SanecMan commented
![торч](https://user-images.githubusercontent.com/36476150/197487071-cd9e767f-c382-4529-a424-0e72133cb0ff.png)

2022-10-24 08:55 UTC, FelineMistress commented
Наше Мнение очень важно для вас!
![1491141056112485402](https://user-images.githubusercontent.com/87654572/197487800-6622d1fd-e5da-45c9-9660-1ba8b436e713.png)