Напукал
frosty-dev/white pull request #1841
Opened 2023-01-26 12:20 UTC by GrishaGold

Перевод заклинаний с касанием. Кусочек продолжения перевода мага.

2023-01-26 14:19 UTC, FelineMistress requested changes

2023-01-26 14:19 UTC, FelineMistress commented on code/modules/spells/spell_types/touch/duffelbag_curse.dm
> +	desc = "Заклинание, которое вызывает демона вещевого мешка на цель, который сбивает их с ног и медленно съедает."
Во первых, не проклятие вещевого мешка, а проклятый мешок (или сумка), он не проклинает твой, он призывает новую
Во вторых оно не сбивает с ног, а замедляет

2023-01-26 14:19 UTC, FelineMistress commented on code/modules/spells/spell_types/touch/duffelbag_curse.dm
> +		to_chat(duffel_victim, span_warning("Мне действительно не хочется сегодня говорить о своем [pick(elaborate_backstory)] с совершенно незнакомыми людьми."))
вот тут у тебя как это должно сопрягаться? говорить о своем военное прошлое / жизнь в колониях с совершенно незнакомыми людьми.
Это как? исправляй или список выше или переделывай предложение

2023-01-26 14:19 UTC, FelineMistress commented on code/modules/spells/spell_types/touch/duffelbag_curse.dm
> +		span_danger("Я чувствую, что что-то привязывается ко мне, и появляется сильное желание обсудить мои [pick(elaborate_backstory)] в конце концов!"),
и тут

2023-01-26 14:19 UTC, FelineMistress commented on code/modules/spells/spell_types/touch/flesh_to_stone.dm
> +	desc = "Это заклинание изменяет вашу руку, наделяя ее способностью переводить живых существ в статуи на длительный период времени."
превращать

2023-01-26 14:19 UTC, FelineMistress commented on code/modules/spells/spell_types/touch/flesh_to_stone.dm
> +	desc = "Вот в чем суть, потому что от плоти к камню так сказала!"
чиво блять

2023-01-26 14:19 UTC, FelineMistress commented on code/modules/spells/spell_types/touch/smite.dm
> +	desc = "Заклинание заряжает вашу руку нечестивой энергией \
точка

2023-01-26 14:19 UTC, FelineMistress commented on code/modules/spells/spell_types/touch/smite.dm
> +		это может быть использовано для прикосновения к жертве чтобы взорвать её тело кровавым месивом"
Если вы дотронетесь ею до жертвы, то её тело взорвется в кровавом месиве.

2023-01-26 14:19 UTC, FelineMistress commented on code/modules/spells/spell_types/touch/smite.dm
> +			human_victim.visible_message(span_danger("[victim] [worn_suit] взрывается превращаясь в лужу запекшейся крови!"))
запятую потерял

2023-01-27 03:58 UTC, Boroda2228 commented on code/modules/spells/spell_types/touch/flesh_to_stone.dm
> +	desc = "Вот в чем суть, потому что от плоти к камню так сказала!"
"That's the bottom line cause Stone Cold said so" - Steve Austin's Quote
Это вообще отсылка к какой-то говне в чужой культуре, локальный мем, его не гуглтранслейтнуть, нужно думоть

2023-01-27 04:35 UTC, IvanDog11 commented on code/modules/spells/spell_types/touch/flesh_to_stone.dm
> +	desc = "Вот в чем суть, потому что от плоти к камню так сказала!"
Их локальный мем нужно переводить на наш локальный мем

2023-01-31 20:04 UTC, FelineMistress approved these changes
Нормально, хотя точку одну лишнюю поставил

2023-01-31 20:04 UTC, merged

2023-02-01 05:40 UTC, Boroda2228 reviewed
похуй наверное

2023-02-01 05:40 UTC, Boroda2228 commented on code/modules/spells/spell_types/touch/duffelbag_curse.dm
> +		"антипровительственных митингах",
провительственных

2023-02-01 05:40 UTC, Boroda2228 commented on code/modules/spells/spell_types/touch/duffelbag_curse.dm
> +		"приятных воспоминания с моим приятелем Валерой",
приятных воспоминанияХ

2023-02-26 17:58 UTC, REBOLUTION228 commented
говно