(WIP) Добавляем урон по органам ИПЦ и Андроидам (НЕНАВИЖУ БЛЯ ПИЗДЕЦ)
frosty-dev/white pull request #1984
Opened 2023-06-29 23:53 UTC by jhnazar

## About The Pull Request
Впиливаем органы Андроидам (они были органические)
Впиливаем урон органам Андроидам и ИПЦ. Да и вообще урон всеем киберорганам
Потрогал ЕМП гранату, теперь она смешная.

Фиксы Еретиков от Читуки09 (ВОЗМОЖНО ФИКСЫ)
code/modules/antagonists/heretic/heretic_knowledge.dm
Тупо заменил стяжки на наручники, ибо искать НЕ кабельные стяжки - бред
code/modules/antagonists/heretic/influences.dm
74 строка how_many_can_we_make += max((NUM_INFLUENCES_PER_HERETIC - heretic_number) + 1, 1)  

Пока не мержить. Не допилено

## Why It's Good For The Game
ИПЦ и Андроиды сосут нехило
Фиксы Еретиков

## Changelog
:cl:
add: Урон от ЕМП органам
add: Изменил начало радиуса опасного взрыва ЕМП гранат с 4 до 1 (чтобы дамажить говноедов)
fix: Фиксим Еретиков
/:cl:

2023-07-09 14:12 UTC, Valtosin requested changes
переделывай нахуй

2023-07-09 14:12 UTC, Valtosin commented on code/game/machinery/rechargestation.dm
> +		if(H.dna.species == /datum/species/android || /datum/species/ipc)
используй isandroid и isipc

2023-07-09 14:12 UTC, Valtosin commented on code/game/machinery/rechargestation.dm
> +	for(var/mob/living/carbon/human/H in occupant)
проверяешь, есть ли в окупанте человек? пиздато

2023-07-09 14:12 UTC, Valtosin commented on code/game/machinery/rechargestation.dm
> +			if(!COOLDOWN_FINISHED(H, repair_cooldown))
всегда FALSE будет

2023-07-09 14:12 UTC, Valtosin commented on code/game/machinery/rechargestation.dm
> +								O.damage += repairs
используй heal_damage() вместо этой хероборы

2023-07-09 14:12 UTC, Valtosin commented on code/modules/mob/living/carbon/carbon_defense.dm
> +		bodypart.emp_act(severity)
в https://github.com/frosty-dev/white/blob/55c2757bd20b49af61ae64a1479edd04e5e87ed0/code/modules/mob/living/living_defense.dm#L376-L381 уже происходит emp_act на все контентсы

2023-07-09 14:12 UTC, Valtosin commented on code/modules/surgery/bodyparts/_bodyparts.dm
> +			owner.Paralyze(100)
```dm
#define EMP_HEAVY 1
#define EMP_LIGHT 2
```

2023-07-09 14:12 UTC, Valtosin commented on code/modules/surgery/organs/eyes.dm
> +		damage += 10/severity
division by zero

2023-07-09 14:12 UTC, Valtosin commented on code/modules/surgery/organs/liver.dm
> +		damage += 10/severity + (10 * emp_vulnerability)/100
тут тоже деление на ноль

2023-07-09 14:12 UTC, Valtosin commented on code/modules/surgery/organs/lungs.dm
> +		damage += 10/severity + (10 * emp_vulnerability)/100
и тут ёпта

2023-07-09 14:12 UTC, Valtosin commented on code/modules/surgery/organs/stomach.dm
> +		damage += 10/severity + (10 * emp_vulnerability)/100
я тебя захуярю

2023-07-10 09:40 UTC, jhnazar commented on code/modules/mob/living/carbon/carbon_defense.dm
> +		bodypart.emp_act(severity)
Эта хуйня у тгшников была. Я просто изменил на получше

2023-07-10 09:40 UTC, jhnazar commented on code/modules/surgery/bodyparts/_bodyparts.dm
> +			owner.Paralyze(100)
В дефайне не имеет смысла, ибо оно и так норм работает

2023-07-10 09:41 UTC, jhnazar commented on code/modules/surgery/organs/eyes.dm
> +		damage += 10/severity
Всмысле на ноль? Урон у меня норм работает?

2023-07-10 09:41 UTC, jhnazar commented on code/modules/surgery/organs/liver.dm
> +		damage += 10/severity + (10 * emp_vulnerability)/100
Всмысле на ноль? Урон у меня норм работает?

2023-07-12 10:38 UTC, jhnazar commented on code/game/machinery/rechargestation.dm
> +								O.damage += repairs
не работает

2023-07-12 10:39 UTC, jhnazar commented on code/game/machinery/rechargestation.dm
> +	for(var/mob/living/carbon/human/H in occupant)
Да. Проверяю, чтобы получить доступ к переменным хумана на проверку species. Если можно как-то по другому, наведи примеры, пожалуйста

2023-07-13 13:03 UTC, jhnazar commented on code/game/machinery/rechargestation.dm
> +		if(H.dna.species == /datum/species/android || /datum/species/ipc)
da

2023-07-16 16:01 UTC, Valtosin requested changes
ААААААААААААААААААААААБЛЯДЬ

2023-07-16 16:01 UTC, Valtosin commented on code/modules/surgery/organs/liver.dm
> +		damage += 10/severity + (10 * emp_vulnerability)/100
> Всмысле на ноль? Урон у меня норм работает

если у тебя `severity` в размере 0, то будет делить на ноль

2023-07-17 12:36 UTC, jhnazar commented on code/modules/surgery/organs/liver.dm
> +		damage += 10/severity + (10 * emp_vulnerability)/100
Так и надо. У тгшников четыре вариции severity:

> /// The (current) highest possible explosion severity.
#define EXPLODE_DEVASTATE 3
/// The (current) middling explosion severity.
#define EXPLODE_HEAVY 2
/// The (current) lowest possible explosion severity.
#define EXPLODE_LIGHT 1
/// The default explosion severity used to mark that an object is beyond the impact range of the explosion.
#define EXPLODE_NONE 0

Собственно если юзер вне радиуса ЕМП, то ему и прилетит ровно ноль урона

2023-07-17 12:51 UTC, jhnazar commented
Я устал дрочить пару строчек кода. Я уже не ебу почему  в `/obj/machinery/recharge_station` виды отхила тела космонавтика по типу `heal_damage()`, `heal_bodypart_damage()`, `heal_overall_damage()`, `M.adjustBruteLoss()` и тому подобное не работает. Одновременно с этим часть кода связанная с отхилом внутренних органов андроида/ипц работает нормально. Короче говоря у меня Skill Issue.

2023-07-17 12:57 UTC, jhnazar commented on code/modules/surgery/bodyparts/_bodyparts.dm
> +			owner.Paralyze(100)
> ```dm
> #define EMP_HEAVY 1
> #define EMP_LIGHT 2
> ```

Я ща глянул в коде и эти дефайны нигде не используются, просто пустышки. Зачем они мне?

2023-07-17 13:22 UTC, jhnazar commented on code/modules/surgery/bodyparts/_bodyparts.dm
> +			owner.Paralyze(100)
а. Я еблан. Понял. Ща

2023-08-05 00:02 UTC, closed without merging