говно
frosty-dev/white pull request #2001
Opened 2023-07-08 18:03 UTC by yafacepravda2

## About The Pull Request
Возвращаем говно на вайт!

## Why It's Good For The Game
Это весело

## Changelog
:cl:
add: Говно
add: R3801U710N two-twenty-eight poo mortar
/:cl:

2023-07-08 18:13 UTC, IvanDog11 commented
Мержите

2023-07-08 18:57 UTC, IvanDog11 approved these changes
Крутое ГОВНО

2023-07-08 20:01 UTC, yafacepravda2 commented
мержите

2023-07-09 07:28 UTC, Fesiks commented
ну это пиздец

2023-07-09 12:07 UTC, jhnazar commented
АХАХАХАХ. ВЕРНИ МОЧУ

2023-07-09 13:58 UTC, Valtosin requested changes
говно, переделывай нахуй

2023-07-09 13:58 UTC, Valtosin commented on white.dme
> -#include "interface\skin.dmf"
чурка верни как было

2023-07-09 17:28 UTC, Valtosin requested changes
переделывай ещё

2023-07-09 17:28 UTC, Valtosin commented on code/modules/mob/living/carbon/human/human_defines.dm
> +	var/pooed = FALSE
вот эту хуйню вообще в трейт надо переделать

2023-07-09 17:28 UTC, Valtosin commented on white/valtos/code/unsorted/poo.dm
> +/atom/proc/wash_poo()
у тебя этот прок нигде не вызывается

2023-07-10 07:34 UTC, Boroda2228 commented on white/valtos/code/unsorted/poo.dm
> +	key_third_person = "shits on the floor"
"срёт прямо на пол!"

2023-07-10 07:38 UTC, Boroda2228 commented on white/valtos/code/unsorted/poo.dm
> +	var/list/random_poo = list("покакунькивает", "срёт", "какает", "производит акт дефекации", "обсирается", "выдавливает какулину")
var/list/random_poo = list("покакунькивает", "срёт", "какает", "производит акт дефекации", "обсирается", "выдавливает какулину", "серит", "гадит", "дрищет", "наваливает", "извергает кучу", "производит удобрение" , "мощно дрищет", "извергает подливу", "откладывает", "сренькает", "устраивает покакушки", "тугосерит", "покакунькивает", "вычпокивает удобрение" , "ахаронит", "выдаёт базу", "накринжил кучку")

2023-07-10 08:18 UTC, yafacepravda2 commented on white/valtos/code/unsorted/poo.dm
> +	var/list/random_poo = list("покакунькивает", "срёт", "какает", "производит акт дефекации", "обсирается", "выдавливает какулину")
Tim Murphy накринжил кучку в рот Чоботар Ибрагим!

2023-07-10 08:20 UTC, yafacepravda2 commented on white/valtos/code/unsorted/poo.dm
> +	key_third_person = "shits on the floor"
![image](https://github.com/frosty-dev/white/assets/85196573/1e44af26-cd05-475e-857e-2bbd3ec07bfb)

2023-07-10 08:22 UTC, yafacepravda2 commented on code/modules/mob/living/carbon/human/human_defines.dm
> +	var/pooed = FALSE
зачем

2023-07-16 16:02 UTC, Valtosin commented on code/modules/mob/living/carbon/human/human_defines.dm
> +	var/pooed = FALSE
затем

2023-08-01 00:03 UTC, closed without merging