Code
frosty-dev/white pull request #204
Opened 2021-08-06 16:58 UTC by Gesugao-san

## Changelog
:cl:
add: авто-закрытие иссуев через 30 дней
tweak: отсортированы рекомендованые расширения для VS Code в алфовитном порядке
fix: изменён отступ в файле конфигурации отладчика с 2 пробелов на 4 пробела, согласно правилам, установленных файлом EditConfig'а
code: отчёт о завершённом раунде стал более подробным и стилизованным: строгий и близкий к футуристичной военной тематике, которая внебрачно спаривалась с гримдарком и _киберпанком_ в тройничке (это про множественные слеши и закос под вывод команды `tree` [вставить смех])
tweak: на уровне ЦК теперь вновь можно использовать мобильные убежища шахтёров, по капсуле которых припасено в каждом поде
/:cl:

2021-08-06 17:06 UTC, Gesugao-san commented
@Valtosin я ~~работаю~~ отдаю долг перед ~~сбродом~~ рабочим классом великого вайта
![image](https://user-images.githubusercontent.com/28023014/128546843-d4223ff4-01e2-41d5-867b-1ee36088cf21.png)

2021-08-06 17:09 UTC, Valtosin commented
Опять бекдоры

2021-08-06 17:09 UTC, RedFoxIV commented
Shruman backdoor

2021-08-06 17:10 UTC, Gesugao-san commented
> Опять бекдоры

@Valtosin дядя, какие бекдоры, ты что за вещи такие плохие говоришь, в каком месте........

2021-08-06 17:11 UTC, Valtosin commented
Не надо меня слапать, я и без этого вижу пуллреквесты прекрасно. Завтра гляну че там точно

2021-08-06 17:13 UTC, Gesugao-san commented
> Не надо меня слапать, я и без этого вижу пуллреквесты прекрасно. Завтра гляну че там точно

хорошо, папочка, буду ждать-с

---

и, блять, ещё линтеры ахуеть, как подробно сломались:
```
Error: Process completed with exit code 1.
```

а интиграционный тест тоже смешно - файл не нашёл:
```
cat: ci_test/data/logs/ci/clean_run.lk: No such file or directory
Error: Process completed with exit code 1.
```

2021-08-07 04:23 UTC, Valtosin requested changes
все HTML теги должны быть в нижнем регистре, также посмотри на другие комментарии

2021-08-07 04:23 UTC, Valtosin commented on code/__HELPERS/roundend.dm
> +		to_chat(world, "<BR><span class='notice'>Аспект раунда был таков: <B>[SSaspects.ca_name]</B> - <i>[SSaspects.ca_desc]</i></span><BR>")
теги должны быть в нижнем регистре

2021-08-07 04:23 UTC, Valtosin commented on code/__HELPERS/roundend.dm
> +	log_game("The round has enfirst_death.")
смысл от этого изменения?

2021-08-07 04:23 UTC, Valtosin commented on code/__HELPERS/roundend.dm
> +	send2adminchat("Server", "Round just enfirst_death.")
плюс

2021-08-07 04:23 UTC, Valtosin commented on code/__HELPERS/roundend.dm
> +	parts += "[FOURSPACES]└ Состояние станции: <B>[mode.station_was_nuked ? "<span class='redtext'>уничтожена системой ядерного самоуничтожения</span>" : "[popcount["station_integrity"] == 100 ? "<span
> системой ядерного самоуничтожения

нюкеры хуй сосали в таком случае?

2021-08-07 04:23 UTC, Valtosin commented on code/__HELPERS/roundend.dm
> +				parts += "[FOURSPACES]├ Зона: <B>[first_death["area"]]</B>"
локация

2021-08-07 04:23 UTC, Valtosin commented on .github/workflows/issues-lock.yml
> +name: 'Lock closed issues'
кто просил

2021-08-07 04:23 UTC, Valtosin commented on code/__HELPERS/roundend.dm
> +	else if(load_admins(TRUE)) //returns true if there was a database failure and the backup was loafirst_death from
ааааааааааааааааааааа

2021-08-07 07:37 UTC, Gesugao-san commented on code/__HELPERS/roundend.dm
> +	log_game("The round has enfirst_death.")
видимо, случайно, так как использовал авто-замену

2021-08-07 07:37 UTC, Gesugao-san commented on code/__HELPERS/roundend.dm
> +	send2adminchat("Server", "Round just enfirst_death.")
https://github.com/frosty-dev/white/pull/204#discussion_r684599185

2021-08-07 07:39 UTC, Gesugao-san commented on code/__HELPERS/roundend.dm
> +	parts += "[FOURSPACES]└ Состояние станции: <B>[mode.station_was_nuked ? "<span class='redtext'>уничтожена системой ядерного самоуничтожения</span>" : "[popcount["station_integrity"] == 100 ? "<span
> > системой ядерного самоуничтожения
> 
> нюкеры хуй сосали в таком случае?

или блоб?

2021-08-07 07:39 UTC, Gesugao-san commented on code/__HELPERS/roundend.dm
> +				parts += "[FOURSPACES]├ Зона: <B>[first_death["area"]]</B>"
оки

2021-08-07 07:39 UTC, Gesugao-san commented on code/__HELPERS/roundend.dm
> +	else if(load_admins(TRUE)) //returns true if there was a database failure and the backup was loafirst_death from
автозамена, откачу

2021-08-07 07:40 UTC, Gesugao-san commented on .github/workflows/issues-lock.yml
> +name: 'Lock closed issues'
@RedFoxIV
например: https://github.com/frosty-dev/white/issues/175#issuecomment-887974023

2021-08-07 07:40 UTC, Gesugao-san commented on code/__HELPERS/roundend.dm
> +		to_chat(world, "<BR><span class='notice'>Аспект раунда был таков: <B>[SSaspects.ca_name]</B> - <i>[SSaspects.ca_desc]</i></span><BR>")
понял

2021-08-07 15:37 UTC, RedFoxIV commented on .github/workflows/issues-lock.yml
> +name: 'Lock closed issues'
чё я просил

2021-08-10 22:39 UTC, RedFoxIV commented
![изображение](https://user-images.githubusercontent.com/38788538/128943931-4f742389-fe58-4a5c-883f-5b80d0fd11f6.png)

2021-08-11 10:24 UTC, Gesugao-san commented
@RedFoxIV
> чё я просил

> https://github.com/frosty-dev/white/issues/175#issuecomment-887974023

ряльно, хуйня бесполезная

2021-08-11 10:33 UTC, Gesugao-san commented on .github/workflows/issues-lock.yml
> +name: 'Lock closed issues'
это https://github.com/frosty-dev/white/pull/204#issuecomment-896357917

2021-08-11 11:33 UTC, Gesugao-san commented on code/__HELPERS/roundend.dm
> +				parts += "[FOURSPACES]├ Зона: <B>[first_death["area"]]</B>"
![image](https://user-images.githubusercontent.com/28023014/129021916-f85f23e4-3748-4aae-860a-ce843848287e.png)

2021-08-11 16:26 UTC, merged