перевод
frosty-dev/white pull request #508
Opened 2022-01-12 05:15 UTC by Crunch228

2022-01-12 13:34 UTC, Crunch228 commented
А где он там ошибку-то нашел?

2022-01-13 02:22 UTC, Valtosin commented on code/modules/antagonists/eldritch_cult/eldritch_effects.dm
> +			to_chat(human_user,span_userdanger("Потустороннее присутствие разрывает вашу руку, когда вы пытаетесь прикоснуться к разлому в самой ткани реальности!"))
вашу

2022-01-13 16:37 UTC, Crunch228 commented
А где он ошибки видит-то? В вскоде смотрел, всё чистенько

2022-01-13 16:42 UTC, TequilaSunrise272 commented on code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
> +	var/chosen_mob = input("Выберите человека, которого вы хотите проклясть","Ваша цель") as null|anything in sortList(compiled_list, /proc/cmp_mob_realname_dsc)
ебал в зад

2022-01-13 16:42 UTC, TequilaSunrise272 commented on code/modules/antagonists/eldritch_cult/eldritch_antag.dm
> +	handle_clown_mutation(current, mob_override ? null : "Древние знания, описанные в книге, позволяют вам преодолеть свою шутовскую натуру, позволяя эффективно использовать сложные предметы.")
НАМ БЛЯД

2022-01-13 16:45 UTC, Crunch228 commented
@Valtosin привет!

2022-01-13 16:52 UTC, jhnazar commented
Валера, твой сичек просто пиздец. Пофикси блять

2022-01-13 16:59 UTC, jhnazar commented on code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
> +				to_chat(user,span_warning("Моя новая цель выбрана, принеси её нам в жертву [LH.target.real_name]!"))
>Моя
>Принеси нам
"Новая цель выбрана. Нужно принести в жертву [LH.target.real_name]!"

2022-01-13 17:00 UTC, jhnazar commented on code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
> +			to_chat(carbon_user,span_danger("Мои покровители принимают моё подношение"))
"Покровители принимают моё подношение" или "Покровители принимают подношение"

2022-01-13 17:03 UTC, jhnazar commented on code/modules/antagonists/eldritch_cult/eldritch_antag.dm
> +	to_chat(owner, "<span class='cult'>Меня пробил холодный пот, в моей голове зашумел гул, я чувствую, как древние, запретные знания охватывают мой разум. Книга тихо шепчет мне, что тайны, которые она
Тут я бы написал так, хз
"Пробивает холодный пот, в голове шумит, чувствую, как древние, запретные знания охватывают мой разум"

2022-01-13 17:10 UTC, Crunch228 commented on code/modules/antagonists/eldritch_cult/eldritch_antag.dm
> +	to_chat(owner, "<span class='cult'>Меня пробил холодный пот, в моей голове зашумел гул, я чувствую, как древние, запретные знания охватывают мой разум. Книга тихо шепчет мне, что тайны, которые она
потом доделаю

2022-01-13 21:50 UTC, RedFoxIV requested changes
убейте меня

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_antag.dm
> +	Ваша книга позволяет вам исследовать способности. Прочтите это очень внимательно, потому что вы не можете отменить то, что было изучено!<br>\
"it" здесь относится конкретно к книге, а не к какому-то абстрактному "этому"

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_antag.dm
> +		owner.current.log_message("has been converted to the cult of the forgotten ones!", LOG_ATTACK, color="#960000")
это чё такое вообще? нахрена поменял?

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_book.dm
> +	name = "Кодекс Шрама"
Давай не будем переводить имена собственные, особенно если они изначально на латинском.

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_book.dm
> +	. += "\nНажмите на руну трансмутации, чтобы стереть её."
Нажал тебе на нос

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_effects.dm
> +	name = "Родовая руна"
отсебятина какая-то пошла, что значит "родовая руна"?
Начертил родовое дерево родни 3 на 3 тайла и принёс жертву своим цыганским пра-пра-пра-родителям?

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_effects.dm
> +	to_chat(user,span_warning("наш ритуал провалился! Я либо использовал неправильные компоненты, либо упустили что-то важное!"))
Расдвоение личности, обращается к себе во множественном числе

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_effects.dm
> +		to_chat(human_user,span_boldwarning("Я знаю, что лучше не искушать силы, вышедшие из-под вашего контроля!"))
"Я знаю, что лучше..." есть несколько корявый перевод.
"Я знаю" там вообще не к месту, можно убрать, будет лучше.

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_effects.dm
> +			to_chat(human_user,span_danger("Я отдергиваю руку от дыры, когда сверхъестественная энергия мечется, пытаясь зацепиться за само существование!"))
по смыслу перевод правильный
по корявости перевод зашкаливает

Ты бы убрал "когда" и перестроил предложение, чтобы лучше как-то звучало

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_effects.dm
> +		to_chat(human_user,span_boldwarning("Я знаею, что лучше не искушать силы, вышедшие из-под вашего контроля!"))
я знаею

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_items.dm
> +	desc = "Сломав свой клинок, вы получите спасение от ужасной ситуации. (Телепортирует вас на случайную безопасную территорию на вашем текущем уровне z, но уничтожает ваш клинок.)"
z-уровне

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_items.dm
> +		to_chat(user,span_danger("Вы чувствуете, как импульс инопланетного интеллекта обрушивается на ваш разум!"))
alien в данном случае переводится как чужой, а не как инопланетный

мы вообще на станции, а не на планете

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_items.dm
> +	desc = "Этот серповидный клинок обветшал, начал ржаветь. И все же он кусается, разрывая плоть и кости зазубренными, гнилыми зубами."
"Этот серповидный клинок обветшал и покрылся ржавчиной."
железо "начинает" ржаветь сразу при контакте с кислородом, тут это слово неуместно как-то

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_items.dm
> +	desc = "Ядовитый для неверных, но освежающий для тех, кто знает о запредельном."
еретики это не конвертороли, у них нет цели обратить всех в свою веру, собственно, и разделения на верных-неверных тут нет.
"Узко мыслящий" хотя бы.

лично я бы заменил "но" на "однако".

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_items.dm
> +	desc = "Черный, как смола, не отражает никакого света. Рунические символы выстилают внешнюю сторону, с каждой вспышкой вы теряете понимание того, что видите."
руны

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_items.dm
> +	desc = "Черный, как смола, не отражает никакого света. Рунические символы выстилают внешнюю сторону, с каждой вспышкой вы теряете понимание того, что видите."
просто руны

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_items.dm
> +	desc = "Маска, созданная из страданий существования, вы можете посмотреть ей в глаза и заметить, что что-то смотрит на вас в ответ."
можно безвозбранно заменить вторую запятую на точку. зачем растягивать одно предложения, если можно сделать два коротких?

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_items.dm
> +	desc = "Холодная сталь, чистая, совершенная, этот нож может резать пол многими способами, но лишь немногие могут вызвать опасности, которые скрываются за реальностью."
carve подразумевает "вырезать" какие-то формы, фигуры
резать подразумевает тупо резать
нельзя резать "многими способами", у тебя только один способ резать - хуяришь нож в пол и на себя.

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_items.dm
> +	desc = "В течение следующих 60 секунд каждая рана будет исцелять вас, незначительные раны исцеляют 1 тип урона в секунду, умеренное исцеление 3 и критическое исцеление 6. Вы также становитесь невосп
проёб
"minor wounds heal 1 of it's damage type per second" - "незначительные раны исцеляют 1 урон своего типа в секунду." - у тебя какой-то косой перевод. Что значит исцелять 1 тип урона в секунду?
чини

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
> +		to_chat(user, span_warning("На этих предметах нет необходимых отпечатков пальцев или ДНК."))
здесь очевидно, что они необходимы, это слово можно убрать

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
> +				to_chat(user,span_warning("Моя новая цель выбрана, принеси её нам в жертву [LH.target.real_name]!"))
"Моя новая цель выбрана, принеси её нам в жертву Иван Иванов!"
пиздец

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
> +				to_chat(user,span_warning("Цель не может быть найдена для живого сердца."))
"Цель для живого сердца..."
кривой порядок слов, прям очень

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
> +	desc = "Позволяет создавать дополнительные живые сердца, используя сердце, лужу крови и мак. Живые сердца при использовании на руне трансмутации дадут вам человека для охоты и жертвоприношения на ру
они не "дают" человека, они лишь вешают на кого-то мишень и говорят тебе, кто это.
Если бы они прям давали, этот человек телепортировался бы на руну в стане с яблоком во рту.

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
> +	name = "Кодекс Шрама"
опять же, латинский

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
> +	desc = "Позволяет вам создать запасной рубец Кодекса, если вы его потеряли, используя Библию, человеческую кожу, ручку и пару глаз."
запасной кодекс

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
> +	gain_text = "Их рука у твоего горла, но ты Их не видишь."
"<i>Их</i> рука лежит на твоём горле, однако <i>Их</i> не видишь ты."

курсив потому что несколько проблематично выделить заглавной буквой слово лишь из двух букв

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_magic.dm
> +	name = "Пепельный Сдвиг"
passage это проход, а не сдвиг

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_magic.dm
> +	name = "Хватка Мансуса"
Чуть раньше ты переводил Mansus как "Мир древних и забытых"

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_magic.dm
> +	desc = "Направляет энергию в вашу перчатку, высвобождение ее создает волну ржавчины на своем пути."
получается, что не сама волна создаёт ржавчину на своём пути, а именно её высвобождение?
тройка по русскому

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_magic.dm
> +	desc = "На минуту высоздадите вокруг себя огненное кольцо."
высоздадите

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_magic.dm
> +	desc = "Опустошает здоровья близлежащих живых людей, охваченных пламенем. Он исцеляет 10 от каждого типа повреждений на человека. Если цель находится в критическом состоянии, это высасывает из нее п
"Здоровье", а не здоровья
"Исцеляет 10 урона каждого типа за каждого человека."

не понял - "Если цель находится в критическом состоянии, это высасывает из нее последние жизненные силы, убивая ее."  - на что тут ссылается "это"? поменяй на "заклинание" что ли, а то пиздцец же звучит коряво

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_magic.dm
> +	desc = "Вы можете телепортироваться, создаст пузырь урона 3x3 вокруг указанного вами пункта назначения и вашего текущего местоположения. Он имеет минимальный диапазон из 3 плиток и максимальный диап
не знаю, чё там остальные считают, но я лично за перевод "tiles" как "тайлов". ибо чё делать, если ты на лаваленде и вокруг тебя нет плиток?

2022-01-13 21:50 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_magic.dm
> +	desc = "Вызовите пустоту, это притянет всех ближайших людей ближе к вам, оглушит людей, которые уже окружают вас. Если они стоят в диапазоне 4 плиток или ближе, они также сбиваются с ног и применяет
"их сбивает с ног и на мгновение оглушает."

2022-01-13 21:55 UTC, RedFoxIV commented
лол, мерж конфликты

2022-01-14 11:41 UTC, Crunch228 commented on code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
> +				to_chat(user,span_warning("Моя новая цель выбрана, принеси её нам в жертву [LH.target.real_name]!"))
Готово

2022-01-14 11:41 UTC, Crunch228 commented on code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
> +			to_chat(carbon_user,span_danger("Мои покровители принимают моё подношение"))
Пиздец конечно тавтология получилась, пофиксил

2022-01-14 11:42 UTC, Crunch228 commented on code/modules/antagonists/eldritch_cult/eldritch_antag.dm
> +		owner.current.log_message("has been converted to the cult of the forgotten ones!", LOG_ATTACK, color="#960000")
Откатил перевод

2022-01-14 11:42 UTC, Crunch228 commented on code/modules/antagonists/eldritch_cult/eldritch_book.dm
> +	name = "Кодекс Шрама"
Перевёл как "Кодекс Цикатрикса", аналогии не нашел, но звучит хуево.

2022-01-14 11:43 UTC, Crunch228 commented on code/modules/antagonists/eldritch_cult/eldritch_book.dm
> +	. += "\nНажмите на руну трансмутации, чтобы стереть её."
Подкорректировал

2022-01-14 11:43 UTC, Crunch228 commented on code/modules/antagonists/eldritch_cult/eldritch_effects.dm
> +	name = "Родовая руна"
Подкорректировал

2022-01-14 11:43 UTC, Crunch228 commented on code/modules/antagonists/eldritch_cult/eldritch_magic.dm
> +	desc = "Направляет энергию в вашу перчатку, высвобождение ее создает волну ржавчины на своем пути."
Не, энергия из перчатки высвобождает волну ржавчины, так задумывалось. Немного перефразировал и заменил на "Направляет энергию в вашу перчатку, высвобождение её создаст волну ржавчины"

2022-01-14 11:43 UTC, Crunch228 commented on code/modules/antagonists/eldritch_cult/eldritch_magic.dm
> +	desc = "На минуту высоздадите вокруг себя огненное кольцо."
Пофиксил

2022-01-14 11:43 UTC, Crunch228 commented on code/modules/antagonists/eldritch_cult/eldritch_magic.dm
> +	desc = "Опустошает здоровья близлежащих живых людей, охваченных пламенем. Он исцеляет 10 от каждого типа повреждений на человека. Если цель находится в критическом состоянии, это высасывает из нее п
пофиксил

2022-01-14 11:43 UTC, Crunch228 commented on code/modules/antagonists/eldritch_cult/eldritch_magic.dm
> +	desc = "Вы можете телепортироваться, создаст пузырь урона 3x3 вокруг указанного вами пункта назначения и вашего текущего местоположения. Он имеет минимальный диапазон из 3 плиток и максимальный диап
Поменял на тайлы. >не урон 3x3, а пузырь 3x3. Там на деле это выглядит как пузырь, могу заменить на "зону, область" , если не к месту вообще.

2022-01-14 13:29 UTC, RedFoxIV commented
Если найду в себе силы, то посмотрю по приходу домой.
То, что я щас посмотрел, вроде как норм

2022-01-14 13:36 UTC, RedFoxIV commented on code/modules/antagonists/eldritch_cult/eldritch_book.dm
> +	name = "Кодекс Шрама"
Кодекс cicatrix
Кодекс цикатрикс
"Codex cicatrix"
ПАРА вариантов, мб тебе какой-то зайдёт лучше

2022-01-14 22:47 UTC, merged

2022-01-14 22:47 UTC, Valtosin commented
похуй

2022-01-14 23:05 UTC, RedFoxIV commented
в моей голове зашумел гул