Cult p.1
frosty-dev/white pull request #527
Opened 2022-01-15 07:44 UTC by KOSTYARON

Начало культоперевода

2022-01-15 07:49 UTC, KOSTYARON commented
Сука че за хуйня с ошибками

2022-01-15 09:35 UTC, RedFoxIV requested changes
![16141135786550](https://user-images.githubusercontent.com/38788538/149617081-a2ab601a-f6b4-4c6a-a206-e1f348c95877.jpg)

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +	desc = "Подготовь кровавую магию, вырезая руны на своей плоти. Легче делать это с <b>руной усиления</b>."
"Это будет легче с"

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +			to_chat(owner, span_cultitalic("Ты не можешь хранить более [MAX_BLOODCHARGE] заклинаний. <b>Выбери заклинание для удаления.</b>"))
Ты не можешь подготовить больше [] заклинаний.

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +			to_chat(owner, span_cultitalic("<b><u>Ты не можешь хранить более [RUNELESS_MAX_BLOODCHARGE] заклинаний без руны усиления! Выбери заклинание для удаления.</b></u>"))
больше вместо более

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +	to_chat(owner,span_warning("Начинаю вырезать внеземные символы на своей плоти!"))
какие нахуй внеземные блядь?

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +		to_chat(owner, span_warning("Мои травмы издают магическое свечение, я приготовил призыв [new_spell.name]!"))
"издают магическое свечение" звучит как что-то, что написал бы семиклассник в фанфике по своему любимому сраниме

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +		desc += "<br>Наношу <u>[health_cost] увечий</u> своей руке при использовании."
чё за хуйня?

Наносит [] брута руке.

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +			to_chat(owner, span_notice("Мои раны светятся, когда я пробуждаю [name]."))
Мои раны начинают светиться, ...
Я пробуждаю [] и мои раны начинают светиться...

Употребление "когда" на месте "as" меня несколько вымораживает, хотя хуй знает, как тут ещё можно перевести

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +	desc = "Заряжает руку оглушением и онемением при использовании на жертве."
онемение это про потерю тактильной чувствительности

может, потеря голоса?

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +		span_cultitalic("Произношу заклятие, чтобы вызвать ЭМИ из своей руки."))
Произношу проклятые слова, вызывая ЭМ-импульс из моей руки.

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +	desc = "Заряжает твою руку магией, позволяющей заковать жертву в наручники."
проебал "and mute them if successful."

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +			source.desc += "<br><b><u>Осталось [uses] использования</u></b>."
использова_ний_, блядь

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +		source.desc += "<br><b><u>Осталось [uses] использования</u></b>."
использова_ний_, блядь x2

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +		source.desc += "<br><b><u>Осталось [uses] использования</u></b>."
и вообще, я недавно запилил глобальный прок getnoun, используй его
getNoun(uses, одно, два, пять)
getNoun(uses, "использование", "использования", "использований")

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +			origin.visible_message(span_warning("Пыль стекает с руки [user], и [user.ru_who()] испаряет[user.p_s()] с резким треском!") , \
flows применимо не только к жидкости, но и потоку, допустим, пыли в воздухе.

"Стекает" моя моча с твоего лица.

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +			user.visible_message(span_cultitalic("У этой жертвы слишком мало рук, чтобы это сделать!"))
У него недостаточно рук, чтобы заковать его!

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +	desc = "Кандалы, которые связывают руки зловещей магией."
Связывающие руки зловещей магией

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +			to_chat(user, span_cultitalic("Я уже пробуждаю извилистое конструирование!"))
ПХАХАХАХАХАХАХАХ

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +	name = "Извилистое конструирование"
блядь, не заметил сразу и проиграл в штаны, когда увидел ниже в коде
какой ЗАЕБИСЬ просто перевод блядь, ИЗВИЛИСТОЕ КОНСТРУИРОВАНИЕ

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +	name = "Извилистое конструирование"
Искажённое строительство.

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +				to_chat(user, span_warning("Темное облако исходит из моей руки, кружится вокруг железа и превращает его в оболочку!"))
в оболочку чего?

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +				to_chat(user, span_warning("Мне нужно [IRON_TO_CONSTRUCT_SHELL_CONVERSION] железа, чтобы сделать оболочку!"))
оболочку чего?

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +				to_chat(user, span_warning("Темное облако исходит из моей руки, превращая [candidate] в оболочку!"))
оболочку чего?

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +	desc = "Впитывает кровь там, где коснёшься. Прикосновения к культистам и оболочкам будут их лечить. Используй в руке, чтобы произвести продвинутый ритуал."
Впитывает кровь в месте прикосновения.

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +				to_chat(user,span_warning("Кровавые ритуалы не работают с тем, у чего нет крови!"))
не работают на расах, у которых нет крови

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +						to_chat(user,span_warning("Мои кровавые ритуалы восстановили [H == user ? "your" : "[H.ru_ego()]"] крови до безопасного уровня!"))
Восстановили его крови?

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +						to_chat(user,span_warning("Мои кровавые ритуалы восстановили [H == user ? "your" : "[H.ru_ego()]"] крови до безопасного уровня!"))
Восстановили your крови??

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +					to_chat(user,span_cultitalic("Высосал 50 единиц крови у [H]."))
50u

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +			to_chat(user, span_cultitalic("Решаю не проводить великий кровавый ритуал."))
"ритуал крови" что ли..

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/cargo/bounties/engineering.dm
> +	name = "Излучатель"
оставь эмиттер, содомит

2022-01-15 09:35 UTC, RedFoxIV commented on code/modules/cargo/bounties/engineering.dm
> +	description = "Мы думаем, что в конструкции излучателя вашей станции может быть дефект, основанный на огромном количестве отслоений, которые, похоже, видит ваш сектор. Отправьте нам один из ваших."
пр на перевод культа, ты чё не культ трогаешь

2022-01-15 09:35 UTC, RedFoxIV commented
![image](https://user-images.githubusercontent.com/38788538/149617099-6ea3a90d-a092-464d-8522-8055937feb27.png)
лол

2022-01-15 09:47 UTC, Valtosin commented
отлично

2022-01-15 09:59 UTC, KOSTYARON commented on code/modules/antagonists/cult/blood_magic.dm
> +	desc = "Заряжает руку оглушением и онемением при использовании на жертве."
![image](https://user-images.githubusercontent.com/87004448/149617773-322301e1-eb30-45d0-9551-a65fbbb9a0e8.png)

2022-01-15 09:59 UTC, KOSTYARON commented on code/modules/antagonists/cult/blood_magic.dm
> +		desc += "<br>Наношу <u>[health_cost] увечий</u> своей руке при использовании."
Брут это брейнрот, за который людей банят на вайте

2022-01-15 10:00 UTC, KOSTYARON commented on code/modules/antagonists/cult/blood_magic.dm
> +	to_chat(owner,span_warning("Начинаю вырезать внеземные символы на своей плоти!"))
Если придумаю какое-то прикольное слово на замену, а не "ненатуральные" или "неестественные", то изменю

2022-01-15 10:00 UTC, KOSTYARON commented on code/modules/antagonists/cult/blood_magic.dm
> +			to_chat(owner, span_cultitalic("<b><u>Ты не можешь хранить более [RUNELESS_MAX_BLOODCHARGE] заклинаний без руны усиления! Выбери заклинание для удаления.</b></u>"))
Ты не можешь хранить более 5 заклинаний без руны усиления! Че не так?

2022-01-15 10:00 UTC, KOSTYARON commented on code/modules/antagonists/cult/blood_magic.dm
> +			to_chat(owner, span_cultitalic("Ты не можешь хранить более [MAX_BLOODCHARGE] заклинаний. <b>Выбери заклинание для удаления.</b>"))
Тож самое, что и ниже

2022-01-15 10:01 UTC, KOSTYARON commented on code/modules/antagonists/cult/blood_magic.dm
> +	desc = "Подготовь кровавую магию, вырезая руны на своей плоти. Легче делать это с <b>руной усиления</b>."
Почему нельзя так, как сделал это я?? Никому не нужное самомнение?

2022-01-15 10:02 UTC, KOSTYARON commented on code/modules/antagonists/cult/blood_magic.dm
> +		span_cultitalic("Произношу заклятие, чтобы вызвать ЭМИ из своей руки."))
Нахуя ЭМ-импульс, если ЭМИ  и есть электромагнитный импульс? Тем более проклятые слова звучит как хуйня. Заклятие получше подходит. Проклятие относится к человеку, а заклятие это в целом.

2022-01-15 10:02 UTC, KOSTYARON commented on code/modules/antagonists/cult/blood_magic.dm
> +	desc = "Заряжает твою руку магией, позволяющей заковать жертву в наручники."
Перевод откатился, пофикшу.

2022-01-15 10:03 UTC, KOSTYARON commented on code/modules/antagonists/cult/blood_magic.dm
> +			source.desc += "<br><b><u>Осталось [uses] использования</u></b>."
Нужна автосклонялка, но она не работала нормально, когда я тестил, поэтому 4,3,2 использования, так как они встречаются чаще, чем 1, и >6

2022-01-15 10:03 UTC, KOSTYARON commented on code/modules/antagonists/cult/blood_magic.dm
> +		source.desc += "<br><b><u>Осталось [uses] использования</u></b>."
Протыкаю

2022-01-15 10:04 UTC, KOSTYARON commented on code/modules/antagonists/cult/blood_magic.dm
> +			user.visible_message(span_cultitalic("У этой жертвы слишком мало рук, чтобы это сделать!"))
Что то хуйня, что это

2022-01-15 10:04 UTC, KOSTYARON commented on code/modules/antagonists/cult/blood_magic.dm
> +	name = "Извилистое конструирование"
Ок

2022-01-15 10:05 UTC, KOSTYARON commented on code/modules/antagonists/cult/blood_magic.dm
> +				to_chat(user, span_warning("Темное облако исходит из моей руки, кружится вокруг железа и превращает его в оболочку!"))
оболочку культиста, ебаный ты в рот, это понятно как только ты юзаешь спелл. В описании всё расписано.

2022-01-15 10:05 UTC, TequilaSunrise272 commented on code/modules/antagonists/cult/blood_magic.dm
> +						to_chat(user,span_warning("Мои кровавые ритуалы восстановили [H == user ? "your" : "[H.ru_ego()]"] крови до безопасного уровня!"))
порвался

2022-01-15 10:05 UTC, KOSTYARON commented on code/modules/antagonists/cult/blood_magic.dm
> +	desc = "Впитывает кровь там, где коснёшься. Прикосновения к культистам и оболочкам будут их лечить. Используй в руке, чтобы произвести продвинутый ритуал."
Ок

2022-01-15 10:05 UTC, TequilaSunrise272 commented
![image](https://user-images.githubusercontent.com/27878805/149617929-bdece7fa-2d43-48aa-a3bf-514a02ae09f0.png)
 ох блядь cuming

2022-01-15 10:06 UTC, KOSTYARON commented on code/modules/antagonists/cult/blood_magic.dm
> +				to_chat(user,span_warning("Кровавые ритуалы не работают с тем, у чего нет крови!"))
Не только расы. Обычный слайм это не раса, поэтому уж лучше мой вариант.

2022-01-15 10:07 UTC, KOSTYARON commented on code/modules/antagonists/cult/blood_magic.dm
> +						to_chat(user,span_warning("Мои кровавые ритуалы восстановили [H == user ? "your" : "[H.ru_ego()]"] крови до безопасного уровня!"))
Я думал, что там число тоже будет. Подправлю

2022-01-15 10:08 UTC, KOSTYARON commented on code/modules/antagonists/cult/blood_magic.dm
> +					to_chat(user,span_cultitalic("Высосал 50 единиц крови у [H]."))
Ладно

2022-01-15 10:08 UTC, KOSTYARON commented on code/modules/antagonists/cult/blood_magic.dm
> +			to_chat(user, span_cultitalic("Решаю не проводить великий кровавый ритуал."))
Синхронизирую с остальной хуйнёй

2022-01-15 10:08 UTC, KOSTYARON commented on code/modules/cargo/bounties/engineering.dm
> +	name = "Излучатель"
Бёрн брут локер рум чел

2022-01-15 10:08 UTC, KOSTYARON commented on code/modules/cargo/bounties/engineering.dm
> +	description = "Мы думаем, что в конструкции излучателя вашей станции может быть дефект, основанный на огромном количестве отслоений, которые, похоже, видит ваш сектор. Отправьте нам один из ваших."
Оно после прошлого прки не залилось

2022-01-15 10:48 UTC, jhnazar commented on code/modules/antagonists/cult/blood_magic.dm
> +	desc = "Подготовь кровавую магию, вырезая руны на своей плоти. Легче делать это с <b>руной усиления</b>."
Версия Редфокса звучит получше

2022-01-15 10:49 UTC, jhnazar commented on code/modules/antagonists/cult/blood_magic.dm
> +			to_chat(owner, span_cultitalic("<b><u>Ты не можешь хранить более [RUNELESS_MAX_BLOODCHARGE] заклинаний без руны усиления! Выбери заклинание для удаления.</b></u>"))
От первого лица блять. "Не могу хранить более чем [RUNELESS_MAX_BLOODCHARGE]..."

2022-01-15 10:49 UTC, jhnazar commented on code/modules/antagonists/cult/blood_magic.dm
> +			to_chat(owner, span_cultitalic("Ты не можешь хранить более [MAX_BLOODCHARGE] заклинаний. <b>Выбери заклинание для удаления.</b>"))
От первого лица блять. "Не могу хранить более чем [RUNELESS_MAX_BLOODCHARGE]..."

2022-01-15 10:50 UTC, jhnazar commented on code/modules/antagonists/cult/blood_magic.dm
> +	to_chat(owner,span_warning("Начинаю вырезать внеземные символы на своей плоти!"))
Может просто написать "странные" и не ебать мозги?

2022-01-15 10:52 UTC, jhnazar commented on code/modules/antagonists/cult/blood_magic.dm
> +		to_chat(owner, span_warning("Мои травмы издают магическое свечение, я приготовил призыв [new_spell.name]!"))
> "издают магическое свечение" звучит как что-то, что написал бы семиклассник в фанфике по своему любимому сраниме

А как лучше? Костя тут норм написал, только вот я бы написал "Мои травмы издают магическое свечение. Призыв [new_spell.name] готов!"

2022-01-15 17:47 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +		to_chat(owner, span_warning("Мои травмы издают магическое свечение, я приготовил призыв [new_spell.name]!"))
хз, мне глаза режет. Твоя версия лучше впрочем

2022-01-15 17:47 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +		desc += "<br>Наношу <u>[health_cost] увечий</u> своей руке при использовании."
я тебя забаню

2022-01-15 17:48 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +	desc = "Заряжает руку оглушением и онемением при использовании на жертве."
у вас хуй онемел

2022-01-15 17:48 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +		span_cultitalic("Произношу заклятие, чтобы вызвать ЭМИ из своей руки."))
Проклял твой хуй.

2022-01-15 17:50 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +				to_chat(user,span_warning("Кровавые ритуалы не работают с тем, у чего нет крови!"))
может тогда лучше "у кого"?

2022-01-15 17:50 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +						to_chat(user,span_warning("Мои кровавые ритуалы восстановили [H == user ? "your" : "[H.ru_ego()]"] крови до безопасного уровня!"))
>число
>"[H.ru_ego()]"

>порвался.

2022-01-15 17:51 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +			to_chat(owner, span_cultitalic("Ты не можешь хранить более [MAX_BLOODCHARGE] заклинаний. <b>Выбери заклинание для удаления.</b>"))
Я не могу подготовить больше [] заклинаний.

fix

2022-01-15 17:52 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +			to_chat(owner, span_cultitalic("<b><u>Ты не можешь хранить более [RUNELESS_MAX_BLOODCHARGE] заклинаний без руны усиления! Выбери заклинание для удаления.</b></u>"))
"более" ухо режет в данном контексте

2022-01-15 17:52 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +		to_chat(owner, span_warning("Мои травмы издают магическое свечение, я приготовил призыв [new_spell.name]!"))
мб "Мои раны светятся от наполняющей их силы"?

2022-01-15 17:54 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +		desc += "<br>Наношу <u>[health_cost] увечий</u> своей руке при использовании."
fix it

2022-01-15 17:55 UTC, RedFoxIV commented on code/modules/antagonists/cult/blood_magic.dm
> +		span_cultitalic("Произношу заклятие, чтобы вызвать ЭМИ из своей руки."))
"произношу, вызывая" вместо "произношу, чтобы вызвать"

первое - элегантно, загадочно, большой нефритовый стержень энергия
второе - банально, серо, вкус мочи

2022-01-15 17:57 UTC, RedFoxIV commented on code/modules/cargo/bounties/engineering.dm
> +	name = "Излучатель"
грифон репы

2022-01-15 17:57 UTC, RedFoxIV commented
каждый пр в этой репе - отдельный щитпост

2022-01-26 13:12 UTC, RedFoxIV commented
умер?

2022-01-27 07:41 UTC, KOSTYARON commented
У меня пока что руки не доходят протыкать перевод. Мб сегодня-завтра подправлю говно и перепроверю на ошибки. Этот пр пока не закрывай.

2022-01-28 17:24 UTC, KOSTYARON commented
Ошибки исправил. Запускал локалку, всё работало без хуйни и вылетов.

2022-02-05 00:17 UTC, closed without merging