Перевел немного химии, доделал еретика, вернул пробелы и тд и тп
frosty-dev/white pull request #812
Opened 2022-04-12 10:43 UTC by Chituka

2022-04-12 10:50 UTC, Chituka commented
Сука, в чем твоя проблема?

2022-04-12 15:12 UTC, FelineMistress commented on code/modules/surgery/organic_steps.dm
> +	display_pain(target, "Чувству. ужасную боль в своей [ru_gde_zone(parse_zone(target_zone))] [skloname(target.name, DATELNI, target.gender)]!")
Чувствую

2022-04-12 15:18 UTC, FelineMistress commented on code/modules/surgery/tools.dm
> +	name = "Расширитель"
зачем? они специально написаны с маленькой буквы. Если это не датум, а итем то пишется с маленькой. Верни как было.

2022-04-12 15:43 UTC, Chituka commented on code/modules/antagonists/eldritch_cult/knowledge/void_lore.dm
> +	priority_announce("$^@&#*$^@(#&$(@&#^$&#^@# Аристократ пустоты [H.real_name] прибыл, шагайте в вальсе убивающий миры! $^@&#*$^@(#&$(@&#^$&#^@#","#$^@&#*$^@(#&$(@&#^$&#^@#", ANNOUNCER_SPANOMALIES)
Ок, я завтра тогда доделаю нормально

2022-04-12 15:53 UTC, FelineMistress commented on code/modules/antagonists/eldritch_cult/knowledge/void_lore.dm
> +	priority_announce("$^@&#*$^@(#&$(@&#^$&#^@# Аристократ пустоты [H.real_name] прибыл, шагайте в вальсе убивающий миры! $^@&#*$^@(#&$(@&#^$&#^@#","#$^@&#*$^@(#&$(@&#^$&#^@#", ANNOUNCER_SPANOMALIES)
тогда меня потом слапни и замержу

2022-04-13 05:55 UTC, Valtosin requested changes

2022-04-13 05:55 UTC, Valtosin commented on code/modules/uplink/uplink_devices.dm
> +	name = "Старое радио"
не пиши имена предметов с большой буквы, если только это не имя или ещё че-то

2022-04-13 08:03 UTC, merged